/*
 * lab.missions/mission-005.js — Account Takeover
 *
 * Progressive Training Lab dataset for Assignment 005. Consumed by the generic
 * engine in lab.js (imported + spread into LAB_MISSIONS). Mirrors the 5-stage
 * arc proven by mission-001/002/003:
 *   1. Linux triage    — read IDP-MENA auth telemetry on the identity server
 *   2. Auth analysis   — surface the brute-force tells, pin 3 indicators
 *   3. Scope expansion — a reactive identity map fades in
 *   4. SOC correlation — confirm the takeover\u2019s scope/intent, pin 3
 *   5. Containment     — disable, reset/re-enroll, block, monitor, then report
 *
 * Faithful to the MENA Account Takeover scenario: one hostile source
 * (45.83.220.10, bulletproof hosting) brute-forces MFA against privileged
 * accounts (admin_svc, db_admin, net_admin). One login eventually SUCCEEDS —
 * admin_svc, after 46 failures — confirming a takeover. A benign employee
 * 'jdoe' on the office network (10.12.4.8) acts as a false lead to rule out.
 */
export default {
  id: 'mission-005',
  opId: 'OPS-2026-005',
  severity: 'MEDIUM',
  headerTitle: 'Account Takeover — Guided Investigation',
  context: 'MENA Identity · Server: IDP-MENA',
  consoleAriaLabel: 'Guided Account Takeover Investigation',
  mapCap: 'IDENTITY MAP — grows as the takeover unfolds',
  nodeTags: { blocked: 'BLOCKED', cleared: 'MONITORED', secured: 'SECURED' },
  reportKey: 'report',
  seedNodes: ['idp', 'source', 'admins'],
  groups: {
    dock: { 1: 'LINUX', 2: 'AUTH ANALYSIS', 3: 'SOC CORRELATION', 5: 'CONTAINMENT' },
    kit:  { 1: 'LINUX', 2: 'AUTH ANALYSIS', 3: 'SOC CORRELATION', 5: 'CONTAINMENT' },
  },
  prompts: {
    threshold: 3,
    fileLabel: 'analyst@idp-mena: ~/auth',
    filePrompt: 'analyst@idp-mena:~/auth$',
    filePwd: '/var/log/auth',
    socLabel: 'analyst@soc — incident OPS-2026-005',
    socPrompt: 'analyst@soc:~$',
    socPwd: '/home/analyst',
  },
  intro: [
    { t: 'CyberCorp Security Training — Lab 005 · Account Takeover', c: 'head' },
    { t: 'The MENA identity service (IDP-MENA) raised an alarm: a flood of failed multi-factor logins against your most powerful accounts. As the SOC analyst on duty, it lands with you.' },
    { t: 'Your mission: find out who is pounding on these accounts, and whether any', c: 'dim' },
    { t: 'door actually opened. A burst of failures from one source is brute force —', c: 'dim' },
    { t: 'but a single SUCCESS hiding in that burst means the account is already lost.', c: 'dim' },
    { t: 'New here? Click any command on the left to learn what it does (it will not run', c: 'dim' },
    { t: 'until you type it), or open the SOC TOOL KIT for the full list of what you have.', c: 'dim' },
    { t: 'Not sure where to begin? Click HINT (or type `hint`) — the first nudge frames', c: 'dim' },
    { t: 'your approach, and each one after gets more specific, ending with the command.', c: 'dim' },
  ],
  objective: {
    1: 'Triage the identity telemetry: open the auth log and find which outside address keeps failing against your accounts.',
    2: 'Prove it is an attack — surface the tells in the auth traffic, then pin the indicators that matter (3 to continue).',
    3: 'One source rarely targets one account. Begin SOC correlation and confirm the takeover\u2019s scope and intent.',
    4: 'Map the full reach of the assault, find the login that succeeded, then pin your key SOC findings to unlock containment (3 to continue).',
    5: 'Shut it down: disable the compromised account, force a credential reset and MFA re-enroll, and block the source — then file your report. Raising monitoring on the privileged accounts is a smart follow-up.',
  },
  files: [
    { name: 'README.txt', icon: '📘', desc: 'triage notes' },
    { name: 'auth.log', icon: '🗂', desc: 'authentication log', suspect: true },
    { name: 'accounts.txt', icon: '🧩', desc: 'privileged accounts' },
    { name: 'sessions.txt', icon: '📄', desc: 'active sessions' },
    { name: 'baseline.txt', icon: '📊', desc: 'approved geo-list' },
  ],
  fs: {
    'README.txt': [
      'Triage notes — account takeover check',
      '',
      'IDP-MENA flagged a storm of failed MFA logins against privileged accounts.',
      'Your job: confirm whether an outside source is brute-forcing us, and',
      'whether any account was actually taken over.',
      '',
      '  1. list the files in this auth folder',
      '  2. read the auth log and spot the address that keeps failing',
      '  3. pull that address out of the log and see which accounts it hit',
      '',
      'A normal login fails once or twice. A burst of failures from one outside',
      'source against several admin accounts is brute force. Watch closely for a',
      'SUCCESS buried in all those failures — that is a door that opened.',
      '',
      'Not sure how? Press HINT, or open the SOC TOOL KIT for the commands.',
    ],
    'auth.log': [
      '# IDP-MENA authentication log (most recent last)',
      'FAILED mfa admin_svc src=45.83.220.10',
      'FAILED mfa db_admin  src=45.83.220.10',
      'FAILED mfa net_admin src=45.83.220.10',
      'FAILED mfa admin_svc src=45.83.220.10',
      'FAILED mfa admin_svc src=45.83.220.10',
      'FAILED mfa db_admin  src=45.83.220.10',
      'FAILED mfa net_admin src=45.83.220.10',
      'FAILED mfa admin_svc src=45.83.220.10',
      'FAILED mfa db_admin  src=45.83.220.10',
      'FAILED mfa admin_svc src=45.83.220.10',
      'SUCCESS login jdoe src=10.12.4.8 (office)',
      'FAILED mfa net_admin src=45.83.220.10',
      'FAILED mfa admin_svc src=45.83.220.10',
      'FAILED mfa admin_svc src=45.83.220.10',
      'FAILED mfa db_admin  src=45.83.220.10',
      '... (46 consecutive failures against admin_svc from 45.83.220.10) ...',
      'SUCCESS login admin_svc src=45.83.220.10 (after 46 failures)',
      'SUCCESS mfa admin_svc src=45.83.220.10',
    ],
    'accounts.txt': [
      'Privileged accounts on IDP-MENA (high-value targets):',
      '',
      '  admin_svc   service / automation admin   (broad platform rights)',
      '  db_admin    database administrator        (full data access)',
      '  net_admin   network administrator         (firewall + routing)',
      '',
      'These accounts hold the keys to the environment. Any sustained login',
      'pressure against them is treated as a high-priority event.',
    ],
    'sessions.txt': [
      'IDP-MENA active sessions (snapshot):',
      '',
      '  USER       TTY     SRC            NOTE',
      '  jdoe       pts/2   10.12.4.8      office network — normal workday login',
      '  admin_svc  pts/0   45.83.220.10   logged in from an unknown external host',
      '',
      'Note: 10.12.4.8 is on the internal office subnet — jdoe is a regular',
      'employee at their desk. The admin_svc session from an outside address',
      'is the one that does not belong.',
    ],
    'baseline.txt': [
      'Approved login geography for IDP-MENA (reviewed monthly):',
      '',
      '  Region:   MENA corporate offices + approved VPN egress',
      '  Office subnet:  10.12.0.0/16   (e.g. 10.12.4.8)',
      '',
      'Any sign-in from OUTSIDE the approved geo-list deserves a second look.',
      '45.83.220.10 is not in the approved region and not on any allow-list.',
    ],
  },
  fileInvestigation: {
    helpHead: 'Linux basics — investigate the identity telemetry:',
    filesHead: '📂 ~/auth &nbsp; <span>—</span> &nbsp; click a file to <code>cat</code> it',
    railEmpty: 'No evidence yet. Investigate the files, then pin the indicators you find.',
    onCat: {
      'auth.log': {
        note: [{ t: '[!] The same outside address — 45.83.220.10 — fails MFA again and again against admin accounts. That repetition is a red flag.', c: 'warn' }],
        discover: 'failure-burst',
        next: [{ t: 'Next, pull that address out of the auth log to see exactly which accounts it is hammering.', c: 'dim' }],
      },
    },
    grepAha: {
      file: 'auth.log',
      requireUrl: false,
      found: [
        { t: '[+] 45.83.220.10 failed MFA against admin_svc, db_admin AND', c: 'ok' },
        { t: '    net_admin — three privileged accounts from one outside host', c: 'ok' },
        { t: '    in a tight burst. A real user fails once; this is brute force.', c: 'ok' },
      ],
      discover: 'targets-admins',
      advanceTo: 2,
      unlock: [
        { t: '' },
        { t: '── ANALYST TOOLS UNLOCKED ────────────────────────', c: 'head' },
        { t: 'You found the core tell. Auth-analysis tools are now available:', c: 'dim' },
        { t: 'geoip · check accounts · compare baseline. Run them, then PIN each indicator.', c: 'dim' },
      ],
    },
  },
  ind: {
    // Stage 1–2 access indicators (group: access)
    'failure-burst': { group: 'access', kind: 'AUTH', label: 'Burst of failed MFA logins from one source',
      teach: '45.83.220.10 fails the MFA challenge over and over in a tight window. A legitimate user mistypes once or twice; a wall of failures from one source is automated guessing.',
      intel: {
        what: 'A single external address (45.83.220.10) generating a rapid burst of FAILED mfa events on IDP-MENA.',
        technique: 'Auth-log review — read the authentication log and group failures by source address to spot one host that keeps reappearing.',
        why: 'A burst of failures from one outside source is the first, cheapest signal of a brute-force / credential-stuffing attack — it separates an attacker from a fat-fingered user.' } },
    'targets-admins': { group: 'access', kind: 'PATTERN', label: 'One source hammering several admin accounts',
      teach: 'The same host failed MFA against admin_svc, db_admin and net_admin — three privileged accounts. Sweeping multiple high-value logins from one source is the signature of a targeted brute force.',
      intel: {
        what: '45.83.220.10 attempted logins against admin_svc, db_admin and net_admin in quick succession.',
        technique: 'Log analysis — grep the auth log for the suspect address and list every distinct account it tried.',
        why: 'Trying many privileged accounts from one source is an attack, not a login. It tells you the adversary is going straight for the most powerful credentials.' } },
    'hostile-geo': { group: 'access', kind: 'GEOIP', label: 'Source is bulletproof hosting, hostile origin',
      teach: 'GeoIP places 45.83.220.10 on a bulletproof hosting provider — infrastructure rented to abuse and shielded from takedowns. No employee signs in from there.',
      intel: {
        what: '45.83.220.10 geolocates to a bulletproof hosting provider known for shielding abusive traffic.',
        technique: 'GeoIP lookup — resolve the source address to its hosting provider, country, and network type.',
        why: 'Bulletproof hosting is where attacks live, not where employees work. Origin alone moves this from suspicious to hostile.' } },
    'privileged-targets': { group: 'access', kind: 'SCOPE', label: 'Targeted accounts are high-value admins',
      teach: 'admin_svc, db_admin and net_admin are not ordinary users — they hold platform, data and network control. An attacker picking exactly these is after maximum leverage.',
      intel: {
        what: 'The accounts under attack (admin_svc, db_admin, net_admin) are the environment\u2019s most privileged identities.',
        technique: 'Account review — line up the targeted usernames against the inventory of privileged accounts.',
        why: 'Scope of damage follows privilege. Compromising any of these grants broad control, so the attack must be treated as high-priority.' } },
    'outside-geolist': { group: 'access', kind: 'BASELINE', label: 'Source outside the approved geo-list',
      teach: '45.83.220.10 is not in the approved MENA region or on the office subnet — unlike jdoe at 10.12.4.8. The baseline turns "looks foreign" into "is unauthorized".',
      intel: {
        what: '45.83.220.10 does not appear in IDP-MENA\u2019s approved login geography or office subnet.',
        technique: 'Baseline comparison — diff the source\u2019s origin against the approved geo-list and allow-listed subnets.',
        why: 'A baseline is what lets you say a sign-in is unauthorized rather than merely unfamiliar — it rules the office user in and the external source out.' } },
    // Stage 4 SOC correlation indicators (group: soc)
    'compromise-confirmed': { group: 'soc', kind: 'BREACH', label: 'One login SUCCEEDED — account taken over',
      teach: 'Buried after 46 failures, admin_svc finally logged in — SUCCESS — from the same hostile source. The brute force worked: this account is compromised.',
      intel: {
        what: 'admin_svc shows a SUCCESS login from 45.83.220.10 after 46 consecutive failures — a confirmed account takeover.',
        technique: 'Success hunting — scan the auth log for any SUCCESS from the attacker\u2019s source amid the wall of failures.',
        why: 'A burst of failures is an attempt; a SUCCESS in that same burst is a breach. This single line changes the incident from "attack" to "takeover" and forces immediate containment.' } },
    'intel-stuffing': { group: 'soc', kind: 'REPUTATION', label: 'Source listed on credential-stuffing blocklists',
      teach: 'Threat-intel feeds already list 45.83.220.10 as credential-stuffing infrastructure — independent confirmation you are not chasing a false positive.',
      intel: {
        what: 'Threat-intel feeds classify 45.83.220.10 as known credential-stuffing / brute-force infrastructure.',
        technique: 'Reputation lookup — check the source address against intel feeds and blocklists.',
        why: 'Independent corroboration that the source is hostile infrastructure, which justifies blocking it network-wide.' } },
    'ato-pattern': { group: 'soc', kind: 'INTEL', label: 'Activity matches an account-takeover pattern',
      teach: 'Correlating the signals — one source, many admin accounts, an external bulletproof origin, then a SUCCESS — confirms this is an account takeover, not noise.',
      intel: {
        what: 'The combined signals (single source, many privileged accounts, hostile origin, a success after many failures) match a textbook account-takeover.',
        technique: 'Signal correlation — stitch the individual indicators into one verdict instead of judging each alone.',
        why: 'A single failed login is noise; the same source brute-forcing admins until one opens is a confirmed takeover you must act on.' } },
    'siem-corr': { group: 'soc', kind: 'SIEM', label: 'Sensor alerts line up with the brute-force timeline',
      teach: 'The SIEM\u2019s scattered authentication alerts, ordered, retell the same story: one source, a flood of MFA failures, then a breakthrough on admin_svc.',
      intel: {
        what: 'SIEM authentication alerts line up exactly with the brute-force timeline ending in the admin_svc success.',
        technique: 'Alert correlation — order isolated sensor alerts into one timeline tied to the source address.',
        why: 'Turns scattered alerts into one coherent incident: a single coordinated account-takeover, evidence-backed for your report.' } },
  },
  topo: {
    nodes: {
      'idp': { x: 18, y: 54, glyph: '🛡', label: 'IDP-MENA', sub: 'identity server', type: '',
        intel: {
          what: 'The MENA identity service whose auth telemetry tripped the alarm — your starting point.',
          technique: 'Identity triage — verify the alert from the IDP\u2019s own auth log and session data, not the sensor summary alone.',
          why: 'Every investigation needs a confirmed entry point. From here you pivot outward to see who is attacking and what they reached.' } },
      'source': { x: 50, y: 46, glyph: '🛰', label: '45.83.220.10', sub: 'external source', type: 'threat',
        intel: {
          what: 'The unknown external address brute-forcing MFA against privileged accounts.',
          technique: 'Source analysis & GeoIP — identify the host, reputation, and the breadth of accounts it attacked.',
          why: 'A flood of failures can look like noise, but one source hammering many admin accounts cannot be explained away. This is the core of the incident.' } },
      'admins': { x: 50, y: 84, glyph: '👥', label: 'privileged accounts', sub: 'admin_svc · db_admin · net_admin', type: '',
        intel: {
          what: 'The cluster of high-value admin identities the source attacked.',
          technique: 'Account mapping — line up the targeted usernames against the privileged-account inventory.',
          why: 'Going straight for admins shows the attacker wants maximum control, raising the stakes of even a single success.' } },
      'compromised': { x: 84, y: 70, glyph: '💀', label: 'admin_svc', sub: 'taken over', type: 'threat',
        intel: {
          what: 'The admin_svc account that finally logged in successfully after 46 failures — a confirmed takeover.',
          technique: 'Success hunting — find the SUCCESS line from the attacker\u2019s source amid the failures.',
          why: 'One opened door is the whole incident. Confirming the takeover forces you to disable and reset that account before anything else.' } },
      'attacker': { x: 84, y: 22, glyph: '💀', label: 'stuffing infra', sub: 'flagged by intel', type: 'threat',
        intel: {
          what: 'The credential-stuffing infrastructure behind the source IP, already flagged by threat-intel feeds.',
          technique: 'Reputation pivot — resolve the source to its hosting/reputation and check intel blocklists.',
          why: 'Confirming hostile infrastructure justifies a network-wide block and helps spot other campaigns from the same source.' } },
      'sensor': { x: 17, y: 22, glyph: '📡', label: 'SIEM sensors', sub: 'auth telemetry', type: '',
        intel: {
          what: 'The identity sensors and SIEM that recorded the authentication activity.',
          technique: 'Alert correlation — order the sensor alerts into one timeline tied to the source.',
          why: 'The sensor record is your evidence trail — it proves the brute force happened and ties every failure to one source.' } },
    },
    links: [
      { a: 'source', b: 'idp',
        intel: {
          what: 'IDP-MENA received a flood of failed MFA logins from the external source.',
          technique: 'Auth-log review — group the failures by source address to surface the repeat offender.',
          why: 'This connection turns "odd auth noise" into a confirmed external source attacking the identity service.' } },
      { a: 'source', b: 'admins',
        intel: {
          what: 'The source attacked multiple privileged accounts in quick succession.',
          technique: 'Log analysis — list every distinct account the source tried.',
          why: 'Many admin accounts from one source is a brute force, not a login — the technical core of the attack.' } },
      { a: 'source', b: 'compromised',
        intel: {
          what: 'The source eventually logged into admin_svc successfully after 46 failures.',
          technique: 'Success hunting — locate the SUCCESS event from the attacker\u2019s address.',
          why: 'This is the line that confirms a takeover: the brute force broke through on a privileged account.' } },
      { a: 'source', b: 'attacker',
        intel: {
          what: 'The source IP belongs to known credential-stuffing infrastructure.',
          technique: 'Reputation lookup — map the source to its intel classification.',
          why: 'Tying the source to flagged infrastructure justifies blocking it network-wide.' } },
      { a: 'sensor', b: 'source', danger: true,
        intel: {
          what: 'SIEM sensors recorded the source\u2019s authentication attempts in sequence.',
          technique: 'Order the sensor alerts into one timeline keyed to the source.',
          why: 'one source → many admin accounts → one success: the takeover, corroborated end to end.' } },
    ],
  },
  tools: [
    { key: 'ls',   cmd: 'ls',                       unlock: 1, icon: '📁', name: 'List files', hint: 'ls' },
    { key: 'cat',  cmd: 'cat auth.log',             unlock: 1, icon: '📄', name: 'Read auth log', hint: 'cat <file>' },
    { key: 'grep', cmd: 'grep 45.83.220.10 auth.log', unlock: 1, icon: '🔍', name: 'Find failures', hint: 'grep <pat> <file>' },

    { key: 'geoip', cmd: 'geoip 45.83.220.10', unlock: 2, icon: '🌐', name: 'GeoIP source', hint: 'geoip <ip>',
      run: { already: 'Already located — see the evidence board.', discover: 'hostile-geo', output: [
        { t: 'IP:        45.83.220.10' },
        { t: 'Provider:  Bulletproof Hosting (abuse-tolerant)', c: 'warn' },
        { t: 'Region:    outside approved MENA geography', c: 'warn' },
        { t: '[+] Hostile hosting origin — no employee signs in from here.', c: 'ok' },
      ] } },
    { key: 'accounts', cmd: 'check accounts', unlock: 2, icon: '🧩', name: 'Check accounts', hint: 'check accounts',
      run: { already: 'Already checked — see the evidence board.', discover: 'privileged-targets', output: [
        { t: 'accounts attacked by 45.83.220.10:', c: '' },
        { t: '  admin_svc · db_admin · net_admin', c: 'warn' },
        { t: '  all three are PRIVILEGED admin accounts', c: 'warn' },
        { t: '[+] The attacker is going straight for the high-value credentials.', c: 'ok' },
      ] } },
    { key: 'baseline', cmd: 'compare baseline', unlock: 2, icon: '📊', name: 'Compare baseline', hint: 'compare baseline',
      run: { already: 'Already compared — see the evidence board.', discover: 'outside-geolist', output: [
        { t: 'checking 45.83.220.10 against approved geo-list …', c: 'dim' },
        { t: '10.12.4.8     -> office subnet (jdoe — benign)', c: '' },
        { t: '45.83.220.10  -> NOT in approved region', c: 'warn' },
        { t: '[+] The source is unauthorized; the office user is ruled out.', c: 'ok' },
      ] } },

    { key: 'success', cmd: 'find success', unlock: 3, icon: '🚪', name: 'Find success', hint: 'find success',
      run: { already: 'Already found — see the evidence board.', advanceTo: 4, addNode: 'compromised', discover: 'compromise-confirmed', output: [
        { t: 'scanning auth log for SUCCESS from 45.83.220.10 …', c: 'dim' },
        { t: 'SUCCESS login admin_svc src=45.83.220.10 (after 46 failures)', c: 'warn' },
        { t: 'SUCCESS mfa admin_svc src=45.83.220.10', c: 'warn' },
        { t: '[+] The brute force broke through — admin_svc is COMPROMISED.', c: 'ok' },
      ] } },
    { key: 'intel', cmd: 'intel 45.83.220.10', unlock: 3, icon: '⚲', name: 'Threat intel', hint: 'intel <ip>',
      run: { already: 'Already checked — see the evidence board.', advanceTo: 4, addNode: 'attacker', discover: 'intel-stuffing', output: [
        { t: '45.83.220.10  ->  threat-intel feeds', c: '' },
        { t: '  verdict: KNOWN credential-stuffing / brute-force infrastructure', c: 'warn' },
        { t: '  listed on multiple stuffing blocklists this week', c: 'warn' },
      ] } },
    { key: 'correlate', cmd: 'correlate ato', unlock: 3, icon: '🧭', name: 'Correlate pattern', hint: 'correlate ato',
      run: { already: 'Already reviewed — see the evidence board.', advanceTo: 4, discover: 'ato-pattern', output: [
        { t: 'correlating: one source · many admins · hostile origin · a success', c: '' },
        { t: '[+] Signals match a textbook account-takeover.', c: 'ok' },
      ] } },
    { key: 'review', cmd: 'review alerts', unlock: 3, icon: '🚨', name: 'Review alerts', hint: 'review alerts',
      run: { already: 'Already reviewed — see the evidence board.', advanceTo: 4, addNode: 'sensor', discover: 'siem-corr', output: [
        { t: 'SIEM correlation:', c: 'head' },
        { t: '  flood of FAILED mfa events from 45.83.220.10 across admin accounts' },
        { t: '  same source, sub-second spacing, ending in admin_svc success', c: 'warn' },
        { t: '[+] Sensor alerts confirm one coordinated takeover.', c: 'ok' },
      ] } },

    { key: 'disable', cmd: 'disable account',   unlock: 5, icon: '🚫', name: 'Disable account', hint: 'disable account' },
    { key: 'reset',   cmd: 'reset credentials', unlock: 5, icon: '🔑', name: 'Reset credentials', hint: 'reset credentials' },
    { key: 'block',   cmd: 'block source',      unlock: 5, icon: '⊘', name: 'Block source', hint: 'block source' },
    { key: 'monitor', cmd: 'raise monitoring',  unlock: 5, icon: '📡', name: 'Raise monitoring', hint: 'raise monitoring' },
    { key: 'report',  cmd: 'submit report',     unlock: 5, icon: '📨', name: 'Submit report', hint: 'submit report' },
  ],
  verb: {
    geoip: 'geoip', check: 'accounts', compare: 'baseline',
    find: 'success', intel: 'intel', correlate: 'correlate', review: 'review',
    disable: 'disable', reset: 'reset', block: 'block', raise: 'monitor', submit: 'report',
  },
  doc: {
    ls:      { purpose: 'Lists every file in the folder you are currently in.',
               learn: 'Before you can investigate anything, you have to know what is in front of you. `ls` ("list") prints the contents of the auth folder so you can spot the telemetry exported from the identity server.' },
    cat:     { purpose: 'Prints the full contents of a file to the screen.',
               learn: '`cat` reads a file out to the terminal. Point it at the auth log to see every login attempt against IDP-MENA — and which outside address keeps failing.' },
    grep:    { purpose: 'Searches inside a file and shows only the matching lines.',
               learn: 'An attack hides inside a noisy log. `grep` pulls out only the lines containing a pattern — point it at the suspect address in the auth log to see every account it tried.' },
    geoip:   { purpose: 'Looks up where an internet address is hosted.',
               learn: 'Every sign-in comes from somewhere. `geoip` resolves the source to its hosting provider and region — bulletproof hosting outside your approved geography is a strong attacker tell.' },
    accounts:{ purpose: 'Lists which accounts a source attacked, and how privileged they are.',
               learn: 'A real user signs into their own account. This shows which accounts the source went after — and that they are all high-value admins, the opposite of normal behaviour.' },
    baseline:{ purpose: 'Compares the source against the approved login geography.',
               learn: 'A baseline is the reviewed list of where sign-ins are supposed to come from. Comparing against it turns "this looks foreign" into "this is unauthorized" — and rules out the benign office user.' },
    success: { purpose: 'Scans the log for any login that actually succeeded.',
               learn: 'A wall of failures is only half the story. This hunts for a SUCCESS hidden among them — and finding one from the attacker\u2019s source means an account has been taken over.' },
    intel:   { purpose: 'Checks the source against threat-intelligence feeds.',
               learn: 'Other defenders share what they see. A reputation lookup tells you whether this source is already known as credential-stuffing infrastructure — independent proof you are not chasing a false positive.' },
    correlate:{ purpose: 'Correlates the signals into a single verdict.',
               learn: 'Individual oddities are noise; together they tell a story. This stitches one-source-many-admins-hostile-origin-then-a-success into the conclusion: an account takeover.' },
    review:  { purpose: 'Reviews the related sensor alerts the SIEM raised.',
               learn: 'Your SIEM (the system watching everything) logged pieces of this attack. Reviewing and ordering those alerts builds the timeline that corroborates your findings.' },
    disable: { purpose: 'Disables the compromised account immediately.',
               learn: 'Once an account is taken over, the attacker is logged in as that user. Disabling it cuts their active access at once — the first move when you confirm a takeover.' },
    reset:   { purpose: 'Forces a credential reset and MFA re-enrollment.',
               learn: 'The attacker now knows the password and beat the MFA. Resetting the credential and re-enrolling MFA from scratch is what truly locks them out and restores the account safely.' },
    block:   { purpose: 'Blocks the source address across the network.',
               learn: 'Cutting off the source at the firewall stops it from attacking further accounts and from coming back. Removing the attacker\u2019s reach is core to containment.' },
    monitor: { purpose: 'Raises monitoring on the affected identities.',
               learn: 'A takeover is often the prelude to deeper abuse. Raising monitoring on the privileged accounts means you will catch any follow-up the moment it begins.' },
    report:  { purpose: 'Writes up and closes the incident.',
               learn: 'Every investigation ends with a record: what happened, what you found, and what you did. The report lets the whole team learn and proves the threat was handled.' },
  },
  hintFlow: {
    stage1: [
      { type: 'ran', key: 'ls', hint: 'ls' },
      { type: 'read', file: 'auth.log', hint: 'cat' },
      { hint: 'grep' },
    ],
    stage2: { group: 'access', need: 3, toolsHint: 'authTools', pinHint: 'pinAccess' },
    stage3: { hint: 'socStart' },
    stage4: { group: 'soc', need: 3, toolsHint: 'socTools', pinHint: 'pinSoc' },
    stage5: { required: ['disable', 'reset', 'block'], actHint: 'contain', reportHint: 'report' },
  },
  hints: {
    ls: { id: 'ls', tiers: [
      'Every investigation starts with orientation — get your bearings before you touch anything. You are in the auth telemetry exported from the identity server.',
      'An auth folder holds files, and you cannot reason about what you cannot see. Your first job is to find out which files are actually here.',
      'In Linux, one short two-letter command lists the files in the current folder.',
      'Type `ls` and press Enter to list the files.',
    ] },
    cat: { id: 'cat', tiers: [
      'A good analyst reads the raw evidence first-hand. One file is the authentication log — that is where failed logins show themselves.',
      'You cannot tell who is attacking the accounts without seeing every login attempt. Read the auth log and look for an outside address that keeps failing.',
      "Use the command that prints a file's contents to the screen, followed by the auth log's name.",
      'Type `cat auth.log` to read the authentication log.',
    ] },
    grep: { id: 'grep', tiers: [
      'You have a suspect address now. The wording of a log can hide a pattern, but the accounts it hit cannot — that contrast is the heart of this case.',
      'Separate the suspect from the noise: pull every line about that one address out of the auth log so you can see exactly which accounts it tried.',
      'There is a Linux tool that prints only the lines of a file matching a pattern. Use it on the auth log with the suspect address.',
      'Type `grep 45.83.220.10 auth.log` to surface its login attempts.',
    ] },
    authTools: { id: 'authTools', tiers: [
      'Your job now shifts from reading to proving. The proof is technical: where this source really is, which accounts it hit, and whether it is even an approved origin.',
      'Establish three things: where the source is hosted, which privileged accounts it attacked, and whether it is inside the approved geography.',
      'The dock now has an AUTH ANALYSIS group. Each tool exposes a different tell — the hosting origin, the targeted accounts, and the baseline comparison. Work through them one at a time.',
      'Type `geoip 45.83.220.10` first, then `check accounts` and `compare baseline`.',
    ] },
    pinAccess: { id: 'pinAccess', tiers: [
      'Investigating surfaces evidence, but findings only count once recorded. An analyst builds a case from committed indicators, not loose observations.',
      'Indicators are appearing on the EVIDENCE board to the right — commit the ones that prove a brute-force attack.',
      'Pin at least 3 indicators. You can click an evidence card, or use the pin command in the terminal.',
      'Type `pin all` to pin every indicator you have surfaced.',
    ] },
    socStart: { id: 'socStart', tiers: [
      'Zoom out. A flood of failures is only half the story — find out whether any login actually succeeded and what intel already knows about this source.',
      'Start with the most urgent question: did the brute force break through? Hunt the log for a success before you map the rest.',
      'Use the SOC tools that just unlocked. Start by hunting for a successful login from the attacker.',
      'Type `find success` to check whether an account was taken over.',
    ] },
    socTools: { id: 'socTools', tiers: [
      'Correlation is about scope and certainty: a takeover you only half-understand is one you cannot fully contain. Widen the lens from one failure to the whole story.',
      'Confirm the breach, check the source\u2019s reputation, tie the pattern together, and line up the SIEM\u2019s alerts.',
      'The SOC CORRELATION group widens the lens — the successful login, the source\u2019s reputation, the takeover pattern, and the SIEM timeline. Run each one.',
      'Try `find success`, then `intel 45.83.220.10`, `correlate ato` and `review alerts`.',
    ] },
    pinSoc: { id: 'pinSoc', tiers: [
      'Before you are allowed to act, you have to justify it. Containment without recorded findings is a guess; recorded findings make it an authorized response.',
      'Record the correlation findings you just uncovered so your response is backed by evidence.',
      'Pin at least 3 of your SOC findings on the evidence board.',
      'Type `pin all` to pin your SOC findings.',
    ] },
    contain: { id: 'contain', tiers: [
      'Now you act — but order matters. Containment of a takeover follows a logic: kill the attacker\u2019s active access, restore the account safely, then cut off the source.',
      'Work through the response in that order: disable the compromised account, force a credential reset and MFA re-enroll, then block the source.',
      'The CONTAINMENT group holds your response actions — one disables the compromised account, one resets its credentials, and one blocks the source. Take them all.',
      'Type `disable account`, `reset credentials`, then `block source`.',
    ] },
    report: { id: 'report', tiers: [
      'An incident is not closed until it is documented. The written record is how the next analyst learns from what you did.',
      'Close out the investigation with a written incident report.',
      'Submit your incident report to finish the investigation.',
      'Type `submit report` to close the incident.',
    ] },
  },
  contain: {
    disable: { need: 'compromise-confirmed', label: 'disable account',
               ok: '[+] admin_svc disabled — the attacker\u2019s active session is cut off immediately.',
               nodes: { compromised: 'secured' } },
    reset:   { need: 'compromise-confirmed', label: 'reset credentials',
               ok: '[+] admin_svc credential reset and MFA re-enrolled; the privileged accounts are restored safely.',
               nodes: { compromised: 'secured', admins: 'secured' } },
    block:   { need: 'intel-stuffing', label: 'block source',
               ok: '[+] 45.83.220.10 blocked at the firewall — no further login attempts can reach IDP-MENA.',
               nodes: { source: 'blocked', attacker: 'blocked' } },
    monitor: { need: 'privileged-targets', label: 'raise monitoring',
               ok: '[+] Heightened monitoring raised on all privileged accounts and identity sensors.',
               nodes: { sensor: 'cleared', admins: 'cleared' } },
  },
  containRequired: ['disable', 'reset', 'block'],
  reveal: {
    campaign: [
      { t: '' },
      { t: '── PATTERN DETECTED ──────────────────────────────', c: 'head' },
      { t: 'This is not a few mistyped passwords. One external source is brute-forcing', c: 'warn' },
      { t: 'MFA across privileged accounts — an active ACCOUNT TAKEOVER attempt.', c: 'warn' },
      { t: 'An identity map is opening above the terminal — it will grow as you uncover', c: 'dim' },
      { t: 'more. Hunt the log for a success and check the source against threat intel.', c: 'dim' },
    ],
    containment: [
      { t: '' },
      { t: '── CONTAINMENT AUTHORIZED ────────────────────────', c: 'head' },
      { t: 'Enough evidence is pinned to act. Containment tools are now unlocked.', c: 'ok' },
      { t: 'Each action changes the identity map. When it\u2019s contained, file your incident report to close out.', c: 'dim' },
    ],
  },
  reportDone: [{ t: '[+] Incident report submitted. Account takeover contained.', c: 'ok' }],
  scorecard: {
    title: 'Account takeover contained',
    subLead: 'You started at a Linux terminal with one flagged identity server and worked all the way to a confirmed takeover and full lockout — pinning ',
    subMid: ' indicators and taking ',
    subTail: ' response actions.',
    evHead: 'Attack indicators you identified',
    socHead: 'SOC correlation you performed',
    learned: [
      'Authentication logs are artifacts you can triage from a terminal — <code>ls</code>, <code>cat</code> and <code>grep</code> surface the evidence.',
      'One source against many privileged accounts is an <em>attack</em>, not a login — the pattern proves brute force.',
      '<code>geoip</code> and a baseline turn "unfamiliar" into "unauthorized"; a benign office user (jdoe) is ruled out the same way.',
      'A single SUCCESS buried in a wall of failures means the account is compromised — that one line defines the incident.',
      'Takeover containment is a sequence: disable the account, reset credentials and re-enroll MFA, block the source, raise monitoring, report.',
    ],
  },
};
