/*
 * lab.missions/mission-003.js — Reconnaissance Detection
 *
 * Progressive Training Lab dataset for mission-003 (player-facing Assignment 001). Consumed by the generic
 * engine in lab.js (imported + spread into LAB_MISSIONS). Mirrors the 5-stage
 * arc proven by mission-001/002:
 *   1. Linux triage   — investigate a workstation's exported telemetry
 *   2. Traffic analysis — surface recon indicators, pin 3
 *   3. Scope expansion — a reactive recon map fades in
 *   4. SOC correlation — confirm the scan's scope/intent, pin 3
 *   5. Containment     — block, harden, raise monitoring, then report
 *
 * Faithful to the legacy M3 scenario: one unknown external host (203.0.113.77)
 * systematically probing multiple services; a benign CDN (198.51.100.20) acts
 * as a false lead the analyst learns to rule out.
 */
export default {
  id: 'mission-003',
  opId: 'OPS-2026-001',
  severity: 'HIGH',
  headerTitle: 'Reconnaissance Detection — Guided Investigation',
  context: 'Endpoint Telemetry · Host: WS-4471',
  consoleAriaLabel: 'Guided Reconnaissance Investigation',
  mapCap: 'RECON MAP — grows as you uncover the scan',
  nodeTags: { blocked: 'BLOCKED', cleared: 'MONITORED', secured: 'HARDENED' },
  reportKey: 'report',
  seedNodes: ['workstation', 'scanner'],
  groups: {
    dock: { 1: 'LINUX', 2: 'TRAFFIC ANALYSIS', 3: 'SOC CORRELATION', 5: 'CONTAINMENT' },
    kit:  { 1: 'LINUX BASICS', 2: 'TRAFFIC ANALYSIS', 3: 'SOC CORRELATION', 5: 'CONTAINMENT' },
  },
  prompts: {
    threshold: 3,
    fileLabel: 'analyst@ws-4471: ~/triage',
    filePrompt: 'analyst@ws-4471:~/triage$',
    filePwd: '/home/analyst/triage',
    socLabel: 'analyst@soc — incident OPS-2026-001',
    socPrompt: 'analyst@soc:~$',
    socPwd: '/home/analyst',
  },
  intro: [
    { t: 'CyberCorp Security Training — Lab 001 · Reconnaissance Detection', c: 'head' },
    { t: 'Perimeter sensors flagged unusual traffic to workstation WS-4471. As the SOC analyst on duty, it lands with you.' },
    { t: 'Your mission: find out who this workstation is talking to. Reconnaissance is', c: 'dim' },
    { t: 'the quiet stage before an attack — repeated or unfamiliar connections are its', c: 'dim' },
    { t: 'first fingerprint. A busy log can look noisy, but a scan has a pattern.', c: 'dim' },
    { t: 'What you\'ll practice: reading connection logs and spotting the repeated, unfamiliar contact that gives a scan away — investigate first, act last.', c: 'dim' },
    { t: 'New here? Click any command on the left to learn what it does (it will not run', c: 'dim' },
    { t: 'until you type it), or open the SOC TOOL KIT for the full list of what you have.', c: 'dim' },
    { t: 'Not sure where to begin? Click HINT (or type `hint`) — the first nudge frames', c: 'dim' },
    { t: 'your approach, and each one after gets more specific, ending with the command.', c: 'dim' },
  ],
  objective: {
    1: 'Triage the telemetry: open the connection snapshot and find which outside address keeps coming back.',
    2: 'Prove it is reconnaissance — surface the tells in the traffic, then pin the indicators that matter (3 to continue).',
    3: 'One host rarely scans one box. Begin SOC correlation and confirm the scan\u2019s scope and intent.',
    4: 'Map the full reach of the scan, then pin your key SOC findings to unlock containment (3 to continue).',
    5: 'Shut it down: block the scanner, harden the exposed services, raise monitoring — then file your incident report.',
  },
  framing: {
    1: { suspicion: 'One outside address keeps coming back to the host.',
         question: 'Which external source is the connection snapshot pointing to?',
         why: 'Repeated contact from one source is the first sign of recon.' },
    2: { suspicion: 'The traffic pattern looks like deliberate scanning.',
         question: 'Which tells separate a scan from normal connections?',
         why: 'Proving intent turns "odd traffic" into a reportable indicator.' },
    3: { suspicion: 'One host is rarely the only target of a scan.',
         question: 'How wide is the sweep, and what infrastructure runs it?',
         why: 'Scope and attribution decide whether this is noise or a threat.' },
    4: { suspicion: 'Active reconnaissance is mapping the subnet.',
         question: 'What is the full reach of the scan across your services?',
         why: 'What the attacker enumerated is what they will target next.' },
    5: { suspicion: 'Confirmed reconnaissance against exposed services.',
         question: 'What blocks the scanner and closes what it found?',
         why: 'Containing recon now denies the follow-on attack a foothold.' },
  },
  files: [
    { name: 'README.txt', icon: '📘', desc: 'triage notes' },
    { name: 'connections.txt', icon: '🗂', desc: 'live connection snapshot', suspect: true },
    { name: 'access.log', icon: '📄', desc: 'service access log' },
    { name: 'baseline.txt', icon: '📊', desc: 'known-good peers' },
    { name: 'services.txt', icon: '🧩', desc: 'listening services' },
  ],
  fs: {
    'README.txt': [
      'Triage notes — reconnaissance check',
      '',
      'Sensors flagged odd traffic on WS-4471. Your job: confirm whether an',
      'outside host is probing us, and how far it reached.',
      '',
      '  1. list the files in this triage folder',
      '  2. read the connection snapshot and spot the address that repeats',
      '  3. pull that address out of the access log and see what it touched',
      '',
      'A normal peer connects to one service. A scanner sweeps many. Watch for',
      'one outside address hitting port after port.',
      '',
      'Not sure how? Press HINT, or open the SOC TOOL KIT for the commands.',
    ],
    'connections.txt': [
      'WS-4471 active connections (snapshot)',
      '',
      'PROTO  LOCAL            REMOTE              STATE',
      'tcp    10.4.7.21:51002  203.0.113.77:443    ESTABLISHED',
      'tcp    10.4.7.21:51004  203.0.113.77:80     TIME_WAIT',
      'tcp    10.4.7.21:51006  203.0.113.77:22     SYN_SENT',
      'tcp    10.4.7.21:51008  203.0.113.77:3306   SYN_SENT',
      'tcp    10.4.7.21:50990  198.51.100.20:443   ESTABLISHED   (CDN)',
      'tcp    10.4.7.21:50988  10.4.7.1:53         ESTABLISHED   (DNS)',
    ],
    'access.log': [
      '# service access log (most recent first)',
      '203.0.113.77 -> port 22 (ssh)    probe',
      '203.0.113.77 -> port 80 (http)   probe',
      '203.0.113.77 -> port 443 (https) probe',
      '203.0.113.77 -> port 3306 (mysql) probe',
      '198.51.100.20 -> port 443 (https) content fetch',
      '10.4.7.55 -> port 443 (https) normal session',
    ],
    'baseline.txt': [
      'Known-good external peers for WS-4471 (reviewed monthly):',
      '',
      '  198.51.100.20   Global CDN Services   (software updates, content)',
      '  10.4.7.1        Internal DNS resolver',
      '  10.4.7.9        Internal patch server',
      '',
      'Any external address NOT on this list deserves a second look.',
    ],
    'services.txt': [
      'Services listening on WS-4471:',
      '',
      '  22/tcp    ssh    (remote admin)',
      '  445/tcp   smb    (file sharing)',
      '',
      'Note: this workstation does NOT run http, https, or mysql servers —',
      'so probes against 80/443/3306 are someone testing for doors that',
      'should not exist here.',
    ],
  },
  fileInvestigation: {
    helpHead: 'Linux basics — investigate the exported telemetry:',
    filesHead: '📂 ~/triage &nbsp; <span>—</span> &nbsp; click a file to <code>cat</code> it',
    railEmpty: 'No evidence yet. Investigate the files, then pin the indicators you find.',
    onCat: {
      'connections.txt': {
        note: [{ t: '[!] One outside address — 203.0.113.77 — appears on four different ports. That repetition is a red flag.', c: 'warn' }],
        discover: 'repeat-external',
        next: [{ t: 'Next, pull that address out of the access log to see exactly what it was reaching for.', c: 'dim' }],
      },
    },
    grepAha: {
      file: 'access.log',
      requireUrl: false,
      found: [
        { t: '[+] 203.0.113.77 hit ssh, http, https AND mysql — four different', c: 'ok' },
        { t: '    services from one outside host in seconds. A real peer talks to', c: 'ok' },
        { t: '    one service; this is a systematic sweep. That pattern is recon.', c: 'ok' },
      ],
      discover: 'multi-port-probe',
      advanceTo: 2,
      unlock: [
        { t: '' },
        { t: '── ANALYST TOOLS UNLOCKED ────────────────────────', c: 'head' },
        { t: 'You found the core tell. Traffic-analysis tools are now available:', c: 'dim' },
        { t: 'whois · ports · baseline. Run them, then PIN each indicator.', c: 'dim' },
      ],
    },
  },
  ind: {
    // Stage 1–2 reconnaissance indicators (group: recon)
    'repeat-external': { group: 'recon', kind: 'TRAFFIC', label: 'One outside address connects repeatedly',
      teach: '203.0.113.77 appears again and again across different ports. A legitimate peer uses one service; repetition across many is a scanning signature.',
      intel: {
        what: 'A single external address (203.0.113.77) connecting to WS-4471 over and over, across multiple ports.',
        technique: 'Connection review — read the live socket snapshot and group by remote address to spot one host that keeps reappearing.',
        why: 'Repetition from one outside source is the first, cheapest signal of reconnaissance — it separates a scanner from normal traffic.' } },
    'multi-port-probe': { group: 'recon', kind: 'SCAN', label: 'Systematic probing of multiple services',
      teach: 'The same host touched ssh (22), http (80), https (443) and mysql (3306) in seconds — testing for any open door, the definition of a port sweep.',
      intel: {
        what: '203.0.113.77 probed ssh, http, https and mysql in quick succession.',
        technique: 'Log analysis — grep the access log for the suspect address and list every distinct port it touched.',
        why: 'Sweeping many services from one source is a scan, not a connection. It tells you the attacker is mapping what is exposed before choosing a way in.' } },
    'unregistered-src': { group: 'recon', kind: 'WHOIS', label: 'Source IP is unknown / unregistered',
      teach: 'WHOIS on 203.0.113.77 returns no organisation and no abuse contact — anonymous infrastructure, unlike the named CDN it sits next to.',
      intel: {
        what: '203.0.113.77 resolves to no registered organisation and lists no abuse contact.',
        technique: 'WHOIS lookup — query the registry for ownership, country, and abuse contact of the source IP.',
        why: 'Legitimate services are registered and contactable. Anonymous, unregistered source infrastructure is a strong recon/attacker tell.' } },
    'targeted-ports': { group: 'recon', kind: 'PORTS', label: 'Probed ports the host does not even run',
      teach: 'WS-4471 only listens on ssh and smb — yet the scanner hit http, https and mysql. It is blindly testing for services, not using ours.',
      intel: {
        what: 'The probed ports (80/443/3306) are services WS-4471 does not run at all.',
        technique: 'Port/service comparison — line up the probed ports against what the host actually listens on.',
        why: 'Probing services that do not exist proves the source is guessing, not connecting — a classic discovery sweep looking for any opening.' } },
    'not-in-baseline': { group: 'recon', kind: 'BASELINE', label: 'Source absent from the known-good peer list',
      teach: '203.0.113.77 is not on the reviewed baseline of approved peers — and the CDN it sits beside is. Baselines turn "looks odd" into "is unauthorized".',
      intel: {
        what: '203.0.113.77 does not appear on WS-4471\u2019s reviewed list of known-good external peers.',
        technique: 'Baseline comparison — diff observed connections against the approved peer list to flag the unexpected.',
        why: 'A baseline is what lets you say an address is unauthorized rather than merely unfamiliar — it rules the CDN in and the scanner out.' } },
    // Stage 4 SOC correlation indicators (group: soc)
    'scan-pattern': { group: 'soc', kind: 'INTEL', label: 'Activity matches a known scanning pattern',
      teach: 'Correlating the signals — one source, many ports, no legitimate session — confirms this is reconnaissance, not noise.',
      intel: {
        what: 'The combined signals (single source, many ports, no real session, unregistered owner) match a textbook reconnaissance scan.',
        technique: 'Signal correlation — stitch the individual indicators into one verdict instead of judging each alone.',
        why: 'A single odd packet is noise; the same source sweeping services with no legitimate purpose is a confirmed scan you must act on.' } },
    'multi-host-scope': { group: 'soc', kind: 'SCOPE', label: 'Six other workstations probed by the same source',
      teach: 'WS-4471 was not alone — the same address swept six other endpoints. One report is the tip of the scan.',
      intel: {
        what: 'The same source (203.0.113.77) probed six other workstations, not just WS-4471.',
        technique: 'Cross-host correlation — query the SIEM for every endpoint touched by the source address.',
        why: 'Scope defines your response. A sweep across many hosts is an attacker mapping the whole subnet, not poking one machine.' } },
    'intel-recon': { group: 'soc', kind: 'REPUTATION', label: 'Source flagged as scanning infrastructure',
      teach: 'Threat-intel feeds already list 203.0.113.77 as known scanning/recon infrastructure — independent confirmation you are not chasing a false positive.',
      intel: {
        what: 'Threat-intel feeds already classify 203.0.113.77 as known scanning / reconnaissance infrastructure.',
        technique: 'Reputation lookup — check the source address against intel feeds and blocklists.',
        why: 'Independent corroboration that the source is hostile infrastructure, which justifies a network-wide block.' } },
    'siem-corr': { group: 'soc', kind: 'SIEM', label: 'Sensor alerts line up with the probe timeline',
      teach: 'The SIEM\u2019s scattered sensor alerts, ordered, retell the same story: one source, a burst of probes, across many hosts.',
      intel: {
        what: 'SIEM sensor alerts across the subnet line up exactly with the probe timeline.',
        technique: 'Alert correlation — order isolated sensor alerts into one timeline tied to the source address.',
        why: 'Turns scattered alerts into one coherent incident: a single coordinated reconnaissance sweep, evidence-backed for your report.' } },
  },
  topo: {
    nodes: {
      'workstation': { x: 18, y: 54, glyph: '💻', label: 'WS-4471', sub: 'flagged host', type: '',
        intel: {
          what: 'The workstation whose telemetry tripped the sensors — your starting point.',
          technique: 'Endpoint triage — verify the alert from the host\u2019s own connection and log data, not the sensor summary alone.',
          why: 'Every investigation needs a confirmed entry point. From here you pivot outward to see how far the scan reached.' } },
      'scanner': { x: 50, y: 46, glyph: '🛰', label: '203.0.113.77', sub: 'external source', type: 'threat',
        intel: {
          what: 'The unknown external address sweeping services across the subnet.',
          technique: 'Source analysis & WHOIS — identify the owner, reputation, and the breadth of ports it touched.',
          why: 'Traffic volume can look like noise, but one source touching many services cannot be explained away. This is the core of the incident.' } },
      'svc': { x: 50, y: 84, glyph: '🔌', label: 'ssh · http · https · mysql', sub: 'probed services', type: 'threat',
        intel: {
          what: 'The cluster of services the source probed — including ports WS-4471 does not even run.',
          technique: 'Port-map comparison — list the probed ports against the host\u2019s real listening services.',
          why: 'Probing services that do not exist proves the source is mapping for openings, the hallmark of a discovery scan.' } },
      'peers': { x: 17, y: 22, glyph: '👥', label: '6 other workstations', sub: 'same source', type: '',
        intel: {
          what: 'Six additional endpoints swept by the same external source.',
          technique: 'Cross-host enumeration — query the SIEM for every host the source address touched.',
          why: 'One report is the tip of the scan. Mapping every probed host reveals the true blast radius you must protect.' } },
      'attacker': { x: 84, y: 22, glyph: '💀', label: 'scanning infra', sub: 'flagged by intel', type: 'threat',
        intel: {
          what: 'The reconnaissance infrastructure behind the source IP, already flagged by threat-intel feeds.',
          technique: 'Reputation pivot — resolve the source to its hosting/reputation and check intel feeds.',
          why: 'Confirming hostile infrastructure justifies a network-wide block and helps spot other campaigns from the same source.' } },
      'sensor': { x: 84, y: 70, glyph: '📡', label: 'SIEM sensors', sub: 'subnet telemetry', type: '',
        intel: {
          what: 'The perimeter sensors and SIEM that recorded the probe activity across the subnet.',
          technique: 'Alert correlation — order the sensor alerts into one timeline tied to the source.',
          why: 'The sensor record is your evidence trail — it proves the sweep happened and ties every host to one source.' } },
    },
    links: [
      { a: 'workstation', b: 'scanner',
        intel: {
          what: 'WS-4471 received repeated probes from the external source.',
          technique: 'Connection review — group the host\u2019s sockets by remote address to surface the repeat offender.',
          why: 'This connection turns "odd traffic" into a confirmed external source probing the host.' } },
      { a: 'scanner', b: 'svc',
        intel: {
          what: 'The source probed multiple services in quick succession.',
          technique: 'Log analysis — list every distinct port the source touched.',
          why: 'Many services from one source is a sweep, not a session — the technical core of reconnaissance.' } },
      { a: 'scanner', b: 'peers',
        intel: {
          what: 'The same source swept six other workstations.',
          technique: 'Cross-host correlation — query the SIEM for all endpoints the source touched.',
          why: 'Shared source across many hosts is what makes this a subnet-wide scan, not an isolated probe.' } },
      { a: 'scanner', b: 'attacker',
        intel: {
          what: 'The source IP belongs to known scanning infrastructure.',
          technique: 'Reputation lookup — map the source to its intel classification.',
          why: 'Tying the source to flagged infrastructure justifies blocking it network-wide.' } },
      { a: 'sensor', b: 'scanner', danger: true,
        intel: {
          what: 'SIEM sensors recorded the source\u2019s probes across the subnet.',
          technique: 'Order the sensor alerts into one timeline keyed to the source.',
          why: 'one source → many ports → many hosts: the recon sweep, corroborated end to end.' } },
    ],
  },
  tools: [
    { key: 'ls',   cmd: 'ls',                          unlock: 1, icon: '📁', name: 'List files', hint: 'ls' },
    { key: 'cat',  cmd: 'cat connections.txt',         unlock: 1, icon: '📄', name: 'Read snapshot', hint: 'cat <file>' },
    { key: 'grep', cmd: 'grep 203.0.113.77 access.log', unlock: 1, icon: '🔍', name: 'Find probes', hint: 'grep <pat> <file>' },

    { key: 'whois', cmd: 'whois 203.0.113.77', unlock: 2, icon: '🌐', name: 'WHOIS source', hint: 'whois <ip>',
      run: { already: 'Already looked up — see the evidence board.', discover: 'unregistered-src', output: [
        { t: 'IP:        203.0.113.77' },
        { t: 'OrgName:   Unknown / Unregistered', c: 'warn' },
        { t: 'Country:   --   ·   abuse contact: none on file', c: 'warn' },
        { t: '[+] Anonymous, unregistered source — not a legitimate service.', c: 'ok' },
      ] } },
    { key: 'ports', cmd: 'ports 203.0.113.77', unlock: 2, icon: '🔌', name: 'Probed ports', hint: 'ports <ip>',
      run: { already: 'Already mapped — see the evidence board.', discover: 'targeted-ports', output: [
        { t: 'ports touched by 203.0.113.77:  22, 80, 443, 3306' },
        { t: 'WS-4471 actually listens on:    22 (ssh), 445 (smb)' },
        { t: '[+] 80/443/3306 are doors this host does not even have — blind probing.', c: 'warn' },
      ] } },
    { key: 'baseline', cmd: 'compare baseline', unlock: 2, icon: '📊', name: 'Compare baseline', hint: 'compare baseline',
      run: { already: 'Already compared — see the evidence board.', discover: 'not-in-baseline', output: [
        { t: 'checking 203.0.113.77 against known-good peers …', c: 'dim' },
        { t: '198.51.100.20  -> on baseline (Global CDN — benign)', c: '' },
        { t: '203.0.113.77   -> NOT on baseline', c: 'warn' },
        { t: '[+] The source is unauthorized; the CDN beside it is ruled out.', c: 'ok' },
      ] } },

    { key: 'intel', cmd: 'intel 203.0.113.77', unlock: 3, icon: '⚲', name: 'Threat intel', hint: 'intel <ip>',
      run: { already: 'Already checked — see the evidence board.', advanceTo: 4, addNode: 'attacker', discover: 'intel-recon', output: [
        { t: '203.0.113.77  ->  threat-intel feeds', c: '' },
        { t: '  verdict: KNOWN scanning / reconnaissance infrastructure', c: 'warn' },
        { t: '  seen probing other organisations this week', c: 'warn' },
      ] } },
    { key: 'scope', cmd: 'check hosts', unlock: 3, icon: '👥', name: 'Check scope', hint: 'check hosts',
      run: { already: 'Already checked — see the evidence board.', advanceTo: 4, addNode: 'peers', discover: 'multi-host-scope', output: [
        { t: 'querying SIEM for hosts touched by 203.0.113.77 …', c: 'dim' },
        { t: '7 workstations probed in the last hour (incl. WS-4471).', c: 'warn' },
        { t: '[+] This is a subnet-wide sweep, not a single-host probe.', c: 'ok' },
      ] } },
    { key: 'pattern', cmd: 'correlate recon', unlock: 3, icon: '🧭', name: 'Correlate pattern', hint: 'correlate recon',
      run: { already: 'Already reviewed — see the evidence board.', advanceTo: 4, addNode: 'svc', discover: 'scan-pattern', output: [
        { t: 'correlating: one source · many ports · no real session', c: '' },
        { t: '[+] Signals match a textbook reconnaissance scan.', c: 'ok' },
      ] } },
    { key: 'siem', cmd: 'review alerts', unlock: 3, icon: '🚨', name: 'Review alerts', hint: 'review alerts',
      run: { already: 'Already reviewed — see the evidence board.', advanceTo: 4, addNode: 'sensor', discover: 'siem-corr', output: [
        { t: 'SIEM correlation:', c: 'head' },
        { t: '  burst of SYN probes from 203.0.113.77 across the subnet' },
        { t: '  same source, sequential ports, sub-second spacing', c: 'warn' },
        { t: '[+] Sensor alerts confirm one coordinated sweep.', c: 'ok' },
      ] } },

    { key: 'block',   cmd: 'block ip',        unlock: 5, icon: '⊘', name: 'Block source', hint: 'block ip' },
    { key: 'harden',  cmd: 'harden services', unlock: 5, icon: '🛡', name: 'Harden services', hint: 'harden services' },
    { key: 'monitor', cmd: 'raise monitoring', unlock: 5, icon: '📡', name: 'Raise monitoring', hint: 'raise monitoring' },
    { key: 'watch',   cmd: 'add watchlist',   unlock: 5, icon: '👁', name: 'Watchlist', hint: 'add watchlist' },
    { key: 'report',  cmd: 'submit report',   unlock: 5, icon: '📨', name: 'Submit report', hint: 'submit report' },
  ],
  verb: {
    whois: 'whois', ports: 'ports', compare: 'baseline',
    intel: 'intel', check: 'scope', correlate: 'pattern', review: 'siem',
    block: 'block', harden: 'harden', raise: 'monitor', add: 'watch', submit: 'report',
  },
  doc: {
    ls:     { purpose: 'Lists every file in the folder you are currently in.',
              learn: 'Before you can investigate anything, you have to know what is in front of you. `ls` ("list") prints the contents of the triage folder so you can spot the telemetry exported from the flagged host.' },
    cat:    { purpose: 'Prints the full contents of a file to the screen.',
              learn: '`cat` reads a file out to the terminal. Point it at the connection snapshot to see every address WS-4471 is talking to — and which one keeps coming back.' },
    grep:   { purpose: 'Searches inside a file and shows only the matching lines.',
              learn: 'A scan hides inside a noisy log. `grep` pulls out only the lines containing a pattern — point it at the suspect address in the access log to see every port it touched.' },
    whois:  { purpose: 'Looks up who owns an internet address.',
              learn: 'Every legitimate service is registered to an organisation with an abuse contact. `whois` reveals that ownership — or, for an attacker, the lack of it. Anonymous, unregistered source infrastructure is a strong tell.' },
    ports:  { purpose: 'Lists which ports a source touched, against what the host runs.',
              learn: 'A real peer connects to a service you actually offer. This compares the ports the source probed with the ports WS-4471 truly listens on — probing doors that do not exist is blind discovery.' },
    baseline:{ purpose: 'Compares the source against the known-good peer list.',
              learn: 'A baseline is the reviewed list of addresses this host is supposed to talk to. Comparing against it turns "this looks unfamiliar" into "this is unauthorized" — and rules out benign peers like the CDN.' },
    intel:  { purpose: 'Checks the source against threat-intelligence feeds.',
              learn: 'Other defenders share what they see. A reputation lookup tells you whether this source is already known as scanning infrastructure — independent proof you are not chasing a false positive.' },
    scope:  { purpose: 'Finds every other host the source touched.',
              learn: 'One alert is rarely the whole story. Checking scope reveals how many other workstations the same source swept — the real reach of the reconnaissance.' },
    pattern:{ purpose: 'Correlates the signals into a single verdict.',
              learn: 'Individual oddities are noise; together they tell a story. This stitches one-source-many-ports-no-session into the conclusion: a reconnaissance scan.' },
    siem:   { purpose: 'Reviews the related sensor alerts the SIEM raised.',
              learn: 'Your SIEM (the system watching everything) logged pieces of this sweep. Reviewing and ordering those alerts builds the timeline that corroborates your findings.' },
    block:  { purpose: 'Blocks the source address across the network.',
              learn: 'Cutting off the scanner at the firewall stops it from probing further and from coming back for the openings it found. Removing the attacker\u2019s reach is the first move in containment.' },
    harden: { purpose: 'Closes or restricts the exposed services it probed.',
              learn: 'Reconnaissance maps your doors so an attacker can pick one later. Hardening the probed services shuts those doors before they can be used.' },
    monitor:{ purpose: 'Raises monitoring on the affected hosts.',
              learn: 'A scan is often the prelude to an attack. Raising monitoring on the probed hosts means you will catch the follow-up the moment it begins.' },
    watch:  { purpose: 'Adds the source to the watchlist for future sightings.',
              learn: 'Attackers reuse infrastructure. Adding the source to the watchlist means any future contact from it is flagged immediately, organisation-wide.' },
    report: { purpose: 'Writes up and closes the incident.',
              learn: 'Every investigation ends with a record: what happened, what you found, and what you did. The report lets the whole team learn and proves the threat was handled.' },
  },
  hintFlow: {
    stage1: [
      { type: 'ran', key: 'ls', hint: 'ls' },
      { type: 'read', file: 'connections.txt', hint: 'cat' },
      { hint: 'grep' },
    ],
    stage2: { group: 'recon', need: 3, toolsHint: 'reconTools', pinHint: 'pinRecon' },
    stage3: { hint: 'socStart' },
    stage4: { group: 'soc', need: 3, toolsHint: 'socTools', pinHint: 'pinSoc' },
    stage5: { required: ['block', 'harden', 'monitor'], actHint: 'contain', reportHint: 'report' },
  },
  hints: {
    ls: { id: 'ls', tiers: [
      'Every investigation starts with orientation — get your bearings before you touch anything. You are in the telemetry exported from the flagged workstation.',
      'A triage folder holds files, and you cannot reason about what you cannot see. Your first job is to find out which files are actually here.',
      'In Linux, one short two-letter command lists the files in the current folder.',
      'Type `ls` and press Enter to list the files.',
    ] },
    cat: { id: 'cat', tiers: [
      'A good analyst reads the raw evidence first-hand. One file is the live connection snapshot — that is where odd traffic shows itself.',
      'You cannot tell who the host is really talking to without seeing every address it has open. Read the snapshot and look for one that repeats.',
      "Use the command that prints a file's contents to the screen, followed by the snapshot file's name.",
      'Type `cat connections.txt` to read the connection snapshot.',
    ] },
    grep: { id: 'grep', tiers: [
      'You have a suspect address now. The wording of a log can hide a pattern, but the ports it touched cannot — that contrast is the heart of this case.',
      'Separate the suspect from the noise: pull every line about that one address out of the access log so you can see exactly what it reached for.',
      'There is a Linux tool that prints only the lines of a file matching a pattern. Use it on the access log with the suspect address.',
      'Type `grep 203.0.113.77 access.log` to surface its probes.',
    ] },
    reconTools: { id: 'reconTools', tiers: [
      'Your job now shifts from reading to proving. The proof is technical: who this source really is, and that it was probing, not connecting.',
      'Establish three things: who owns the source, which ports it touched versus what the host runs, and whether it is even an approved peer.',
      'The dock now has a TRAFFIC ANALYSIS group. Each tool exposes a different tell — ownership, the probed ports, and the baseline comparison. Work through them one at a time.',
      'Type `whois 203.0.113.77` first, then `ports 203.0.113.77` and `compare baseline`.',
    ] },
    pinRecon: { id: 'pinRecon', tiers: [
      'Investigating surfaces evidence, but findings only count once recorded. An analyst builds a case from committed indicators, not loose observations.',
      'Indicators are appearing on the EVIDENCE board to the right — commit the ones that prove reconnaissance.',
      'Pin at least 3 indicators. You can click an evidence card, or use the pin command in the terminal.',
      'Type `pin all` to pin every indicator you have surfaced.',
    ] },
    socStart: { id: 'socStart', tiers: [
      'Zoom out. A scan against one box is rarely the whole story — find out whether this source hit others and what intel already knows about it.',
      'Start with the source\u2019s reputation: confirm whether it is known scanning infrastructure before you map the rest.',
      'Use the SOC tools that just unlocked. Start by checking the source against threat intel.',
      'Type `intel 203.0.113.77` to begin the correlation.',
    ] },
    socTools: { id: 'socTools', tiers: [
      'Correlation is about scope: a scan you only half-understand is one you cannot fully contain. Widen the lens from one host to the whole subnet.',
      'Map who else was probed, confirm the pattern is really a scan, and tie the SIEM\u2019s alerts to the source.',
      'The SOC CORRELATION group widens the lens — reputation, scope across hosts, the scan pattern, and the SIEM timeline. Run each one.',
      'Try `check hosts`, then `correlate recon` and `review alerts`.',
    ] },
    pinSoc: { id: 'pinSoc', tiers: [
      'Before you are allowed to act, you have to justify it. Containment without recorded findings is a guess; recorded findings make it an authorized response.',
      'Record the correlation findings you just uncovered so your response is backed by evidence.',
      'Pin at least 3 of your SOC findings on the evidence board.',
      'Type `pin all` to pin your SOC findings.',
    ] },
    contain: { id: 'contain', tiers: [
      'Now you act — but order matters. Containment follows a logic: cut the scanner off, close the doors it found, then watch for the follow-up.',
      'Work through the response in that order: block the source, harden the probed services, then raise monitoring.',
      'The CONTAINMENT group holds your response actions — one blocks the source, one hardens the exposed services, and one raises monitoring on the probed hosts. Take them all.',
      'Type `block ip`, `harden services`, then `raise monitoring`.',
    ] },
    report: { id: 'report', tiers: [
      'An incident is not closed until it is documented. The written record is how the next analyst learns from what you did.',
      'Close out the investigation with a written incident report.',
      'Submit your incident report to finish the investigation.',
      'Type `submit report` to close the incident.',
    ] },
  },
  contain: {
    block:   { need: 'intel-recon', label: 'block ip',
               ok: '[+] 203.0.113.77 blocked at the firewall — no further probes can reach the subnet.',
               nodes: { scanner: 'blocked', attacker: 'blocked' } },
    harden:  { need: 'targeted-ports', label: 'harden services',
               ok: '[+] Exposed services restricted to known peers; the probed doors are closed.',
               nodes: { svc: 'secured', workstation: 'secured' } },
    monitor: { need: 'multi-host-scope', label: 'raise monitoring',
               ok: '[+] Heightened monitoring raised on all 7 probed workstations.',
               nodes: { peers: 'cleared', sensor: 'cleared' } },
    watch:   { need: 'intel-recon', label: 'add watchlist',
               ok: '[+] 203.0.113.77 added to the org-wide watchlist for future sightings.',
               nodes: { attacker: 'blocked' } },
  },
  containRequired: ['block', 'harden', 'monitor'],
  reveal: {
    campaign: [
      { t: '' },
      { t: '── PATTERN DETECTED ──────────────────────────────', c: 'head' },
      { t: 'This is not a single odd connection. One external source is sweeping', c: 'warn' },
      { t: 'services across the subnet — active RECONNAISSANCE against CyberCorp.', c: 'warn' },
      { t: 'A recon map is opening above the terminal — it will grow as you uncover', c: 'dim' },
      { t: 'more. Check the source against threat intel to confirm the infrastructure.', c: 'dim' },
    ],
    containment: [
      { t: '' },
      { t: '── CONTAINMENT AUTHORIZED ────────────────────────', c: 'head' },
      { t: 'Enough evidence is pinned to act. Containment tools are now unlocked.', c: 'ok' },
      { t: 'Each action changes the recon map. When it\u2019s contained, file your incident report to close out.', c: 'dim' },
    ],
  },
  reportDone: [{ t: '[+] Incident report submitted. Reconnaissance contained.', c: 'ok' }],
  scorecard: {
    title: 'Reconnaissance contained',
    subLead: 'You started at a Linux terminal with one flagged host and worked all the way to a subnet-wide block — pinning ',
    subMid: ' indicators and taking ',
    subTail: ' response actions.',
    evHead: 'Reconnaissance indicators you identified',
    socHead: 'SOC correlation you performed',
    learned: [
      'Connections and logs are artifacts you can inspect from a terminal — <code>ls</code>, <code>cat</code> and <code>grep</code> surface the evidence.',
      'Reconnaissance is proven by the <em>pattern</em> — one source, many ports, no real session — not by any single packet.',
      'A baseline and <code>whois</code> turn "unfamiliar" into "unauthorized"; a benign CDN is ruled out the same way.',
      'Containment is a sequence: block the source, harden the probed services, raise monitoring, report.',
    ],
  },
};
