/*
 * lab.missions/mission-004.js — Reconnaissance Sweep
 *
 * Progressive Training Lab dataset for Assignment 004. Consumed by the generic
 * engine in lab.js (imported + spread into LAB_MISSIONS). Mirrors the 5-stage
 * arc proven by mission-001/002/003:
 *   1. Linux triage     — investigate the perimeter firewall's exported logs
 *   2. Log analysis     — surface recon indicators, pin 3
 *   3. Scope expansion  — a reactive perimeter map fades in
 *   4. SOC correlation  — confirm the sweep's scope/intent, pin 3
 *   5. Containment      — block, harden, raise monitoring, then report
 *
 * Faithful to the M4 scenario: an unknown external range (203.0.113.0/24) with
 * many source IPs systematically sweeping 27 distinct service ports across the
 * LATAM perimeter firewall. A benign Google DNS resolver (8.8.8.8) acts as a
 * false lead the analyst learns to rule out. Unlike M3 (one endpoint, one
 * source IP), this is perimeter/firewall-level recon by a whole range.
 */
export default {
  id: 'mission-004',
  opId: 'OPS-2026-004',
  severity: 'MEDIUM',
  headerTitle: 'Reconnaissance Sweep — Guided Investigation',
  context: 'LATAM Perimeter · Firewall: FW-LATAM',
  consoleAriaLabel: 'Guided Reconnaissance Sweep Investigation',
  mapCap: 'PERIMETER MAP — grows as you map the sweep',
  nodeTags: { blocked: 'BLOCKED', cleared: 'MONITORED', secured: 'HARDENED' },
  reportKey: 'report',
  seedNodes: ['perimeter', 'range'],
  groups: {
    dock: { 1: 'LINUX', 2: 'LOG ANALYSIS', 3: 'SOC CORRELATION', 5: 'CONTAINMENT' },
    kit:  { 1: 'LINUX BASICS', 2: 'LOG ANALYSIS', 3: 'SOC CORRELATION', 5: 'CONTAINMENT' },
  },
  prompts: {
    threshold: 3,
    fileLabel: 'analyst@fw-latam: ~/perimeter',
    filePrompt: 'analyst@fw-latam:~/perimeter$',
    filePwd: '/var/log/perimeter',
    socLabel: 'analyst@soc — incident OPS-2026-004',
    socPrompt: 'analyst@soc:~$',
    socPwd: '/home/analyst',
  },
  intro: [
    { t: 'CyberCorp Security Training — Lab 004 · Reconnaissance Sweep', c: 'head' },
    { t: 'The LATAM perimeter firewall (FW-LATAM) is logging a flood of denied connections from outside. As the SOC analyst on duty, it lands with you.' },
    { t: 'Your mission: find out who is knocking on the perimeter, and what they are', c: 'dim' },
    { t: 'looking for. A sweep maps your exposed attack surface before an attack —', c: 'dim' },
    { t: 'many source addresses testing many services is its first fingerprint.', c: 'dim' },
    { t: 'New here? Click any command on the left to learn what it does (it will not run', c: 'dim' },
    { t: 'until you type it), or open the SOC TOOL KIT for the full list of what you have.', c: 'dim' },
    { t: 'Not sure where to begin? Click HINT (or type `hint`) — the first nudge frames', c: 'dim' },
    { t: 'your approach, and each one after gets more specific, ending with the command.', c: 'dim' },
  ],
  objective: {
    1: 'Triage the perimeter logs: open the firewall log and find which outside range keeps getting denied.',
    2: 'Prove it is reconnaissance — surface the tells in the traffic, then pin the indicators that matter (3 to continue).',
    3: 'One probe is rarely the whole picture. Begin SOC correlation and confirm the sweep\u2019s scope and intent.',
    4: 'Map the full reach of the sweep, then pin your key SOC findings to unlock containment (3 to continue).',
    5: 'Shut it down: block the range, harden the exposed perimeter, raise monitoring — then file your incident report.',
  },
  files: [
    { name: 'README.txt', icon: '📘', desc: 'triage notes' },
    { name: 'firewall.log', icon: '🗂', desc: 'perimeter firewall log', suspect: true },
    { name: 'sources.txt', icon: '📄', desc: 'denied source addresses' },
    { name: 'services.txt', icon: '🧩', desc: 'perimeter services' },
    { name: 'baseline.txt', icon: '📊', desc: 'approved externals' },
  ],
  fs: {
    'README.txt': [
      'Triage notes — perimeter reconnaissance check',
      '',
      'FW-LATAM is logging a wall of denied connections from outside. Your job:',
      'confirm whether an external range is probing the perimeter, and how wide',
      'it reached.',
      '',
      '  1. list the files in this perimeter log folder',
      '  2. read the firewall log and spot the address range that repeats',
      '  3. pull that range out of the log and see how many ports it touched',
      '',
      'A normal peer connects to one approved service. A sweep tests many ports',
      'from many addresses in the same neighbourhood. Watch for one /24 range',
      'hitting port after port.',
      '',
      'Not sure how? Press HINT, or open the SOC TOOL KIT for the commands.',
    ],
    'firewall.log': [
      'FW-LATAM perimeter firewall log (most recent first)',
      '',
      'ACTION  SOURCE          -> DEST:PORT          SERVICE',
      'DENY    203.0.113.41    -> 198.51.100.7:22    ssh',
      'DENY    203.0.113.58    -> 198.51.100.7:80    http',
      'DENY    203.0.113.12    -> 198.51.100.7:443   https',
      'DENY    203.0.113.90    -> 198.51.100.7:3389  rdp',
      'DENY    203.0.113.41    -> 198.51.100.7:8080  http-alt',
      'DENY    203.0.113.58    -> 198.51.100.7:3306  mysql',
      'DENY    203.0.113.12    -> 198.51.100.7:22    ssh',
      'DENY    203.0.113.90    -> 198.51.100.7:443   https',
      'ALLOW   8.8.8.8         -> 198.51.100.7:53    dns   (Google DNS resolver)',
    ],
    'sources.txt': [
      'Denied source addresses seen on FW-LATAM (last hour):',
      '',
      '  203.0.113.41',
      '  203.0.113.58',
      '  203.0.113.12',
      '  203.0.113.90',
      '',
      'All four share the same 203.0.113.x prefix — they belong to one /24',
      'network block (203.0.113.0/24). Different last octets, one neighbourhood.',
      '',
      'One address probing is a poke; a whole range probing is a coordinated sweep.',
    ],
    'services.txt': [
      'Services exposed behind FW-LATAM:',
      '',
      '  22/tcp    ssh    (remote admin — restricted)',
      '  443/tcp   https  (public web)',
      '  53/udp    dns    (resolver — outbound only)',
      '',
      'Perimeter scan summary: the firewall counted 27 DISTINCT destination',
      'ports probed by the 203.0.113.0/24 range — including rdp (3389), mysql',
      '(3306) and http-alt (8080) that we do not expose at all.',
      '',
      'Probing 27 services when we publish 3 is someone mapping for any open door.',
    ],
    'baseline.txt': [
      'Approved external peers for the LATAM perimeter (reviewed monthly):',
      '',
      '  8.8.8.8         Google Public DNS resolver   (name resolution — benign)',
      '  198.51.100.9    Partner API gateway',
      '  198.51.100.20   Global CDN Services',
      '',
      'Note: the 203.0.113.0/24 range is NOT approved and appears nowhere on',
      'this list. Any external source not on the baseline deserves a second look.',
    ],
  },
  fileInvestigation: {
    helpHead: 'Linux basics — investigate the exported perimeter logs:',
    filesHead: '📂 ~/perimeter &nbsp; <span>—</span> &nbsp; click a file to <code>cat</code> it',
    railEmpty: 'No evidence yet. Investigate the files, then pin the indicators you find.',
    onCat: {
      'firewall.log': {
        note: [{ t: '[!] Many denied sources — 203.0.113.41, .58, .12, .90 — all sit in one /24 range (203.0.113.0/24). That shared neighbourhood is a red flag.', c: 'warn' }],
        discover: 'shared-range',
        next: [{ t: 'Next, pull that range out of the firewall log to see exactly how many ports it was reaching for.', c: 'dim' }],
      },
    },
    grepAha: {
      file: 'firewall.log',
      requireUrl: false,
      found: [
        { t: '[+] The 203.0.113.0/24 range hit ssh, http, https, rdp, http-alt', c: 'ok' },
        { t: '    AND mysql — many different services from one range in seconds.', c: 'ok' },
        { t: '    A real peer talks to one service; this is a systematic sweep. Recon.', c: 'ok' },
      ],
      discover: 'distributed-probe',
      advanceTo: 2,
      unlock: [
        { t: '' },
        { t: '── LOG ANALYSIS TOOLS UNLOCKED ───────────────────', c: 'head' },
        { t: 'You found the core tell. Log-analysis tools are now available:', c: 'dim' },
        { t: 'whois · count · baseline. Run them, then PIN each indicator.', c: 'dim' },
      ],
    },
  },
  ind: {
    // Stage 1–2 reconnaissance indicators (group: recon)
    'shared-range': { group: 'recon', kind: 'FIREWALL', label: 'Many denied sources share one /24 range',
      teach: 'The denied sources (203.0.113.41, .58, .12, .90) all live in 203.0.113.0/24. A legitimate peer is one address; a cluster from one neighbourhood is a coordinated source.',
      intel: {
        what: 'Several external source addresses, all denied at FW-LATAM, share the single 203.0.113.0/24 network block.',
        technique: 'Firewall log review — read the denied connections and group sources by their network prefix to spot one range behind many addresses.',
        why: 'A whole range acting together is the first, cheapest signal of a coordinated sweep — it separates a distributed scanner from scattered noise.' } },
    'distributed-probe': { group: 'recon', kind: 'SCAN', label: 'One range probing many different services',
      teach: 'The same 203.0.113.0/24 range touched ssh, http, https, rdp, http-alt and mysql in seconds — testing for any open door, the definition of a distributed port sweep.',
      intel: {
        what: 'The 203.0.113.0/24 range probed ssh (22), http (80), https (443), rdp (3389), http-alt (8080) and mysql (3306) in quick succession.',
        technique: 'Log analysis — grep the firewall log for the suspect range and list every distinct destination port it touched.',
        why: 'Sweeping many services from one range is a scan, not a connection. It tells you the attacker is mapping what the perimeter exposes before choosing a way in.' } },
    'unallocated-range': { group: 'recon', kind: 'WHOIS', label: 'Source range is unallocated / unregistered',
      teach: 'WHOIS on 203.0.113.0/24 returns no allocated organisation and no abuse contact — anonymous infrastructure, unlike the named resolver the firewall also logged.',
      intel: {
        what: 'The 203.0.113.0/24 block is unallocated, resolves to no registered organisation, and lists no abuse contact.',
        technique: 'WHOIS lookup — query the registry for ownership, allocation status, country, and abuse contact of the source range.',
        why: 'Legitimate networks are allocated and contactable. Anonymous, unallocated source infrastructure is a strong recon/attacker tell.' } },
    'wide-footprint': { group: 'recon', kind: 'FOOTPRINT', label: '27 distinct ports probed across the perimeter',
      teach: 'The firewall counted 27 distinct destination ports from the range — far more than the 3 services we actually expose. That breadth is blind mapping, not legitimate use.',
      intel: {
        what: 'The 203.0.113.0/24 range probed 27 distinct destination ports, while the perimeter only publishes 3 real services.',
        technique: 'Port/service tally — count the unique ports the range touched and compare against what the perimeter actually exposes.',
        why: 'Probing far more ports than exist proves the source is guessing, not connecting — a classic discovery sweep looking for any opening in the attack surface.' } },
    'not-approved-range': { group: 'recon', kind: 'BASELINE', label: 'Source range absent from approved externals',
      teach: '203.0.113.0/24 is not on the reviewed baseline of approved external peers — and the Google DNS resolver beside it is. Baselines turn "looks odd" into "is unauthorized".',
      intel: {
        what: 'The 203.0.113.0/24 range does not appear on the perimeter\u2019s reviewed list of approved external peers.',
        technique: 'Baseline comparison — diff observed sources against the approved external list to flag the unexpected.',
        why: 'A baseline is what lets you say a range is unauthorized rather than merely unfamiliar — it rules the Google resolver in and the unknown range out.' } },
    // Stage 4 SOC correlation indicators (group: soc)
    'intel-flagged': { group: 'soc', kind: 'REPUTATION', label: 'Range flagged in active threat-intel feeds',
      teach: 'Threat-intel feeds already list 203.0.113.0/24 as scanning/recon infrastructure — flagged in 3 active feeds, independent confirmation you are not chasing a false positive.',
      intel: {
        what: 'Threat-intel feeds classify 203.0.113.0/24 as known scanning / reconnaissance infrastructure — flagged in 3 active feeds.',
        technique: 'Reputation lookup — check the source range against intel feeds and blocklists.',
        why: 'Independent corroboration that the source is hostile infrastructure, which justifies a perimeter-wide block of the whole range.' } },
    'multi-service-scope': { group: 'soc', kind: 'SCOPE', label: 'Sweep spans the full exposed service scope',
      teach: 'The range did not poke one service — it swept the entire exposed perimeter, restricted admin ports and public web alike. One report is the tip of the sweep.',
      intel: {
        what: 'The same range (203.0.113.0/24) probed across the full scope of perimeter services, not a single port.',
        technique: 'Cross-service correlation — query the firewall and SIEM for every service the range touched.',
        why: 'Scope defines your response. A sweep across the whole service surface is an attacker mapping the entire perimeter, not testing one door.' } },
    'sweep-pattern': { group: 'soc', kind: 'INTEL', label: 'Activity matches a known sweep pattern',
      teach: 'Correlating the signals — one range, many ports, sequential probing, no legitimate session — confirms this is a reconnaissance sweep, not noise.',
      intel: {
        what: 'The combined signals (one range, 27 ports, sequential timing, no real session, unallocated owner) match a textbook reconnaissance sweep.',
        technique: 'Signal correlation — stitch the individual indicators into one verdict instead of judging each alone.',
        why: 'A single denied packet is noise; a whole range sweeping services in sequence with no legitimate purpose is a confirmed sweep you must act on.' } },
    'siem-corr': { group: 'soc', kind: 'SIEM', label: 'Sensor alerts line up with the sweep timeline',
      teach: 'The SIEM\u2019s scattered sensor alerts, ordered, retell the same story: one range, a burst of sequential probes, across the perimeter.',
      intel: {
        what: 'SIEM sensor alerts across the perimeter line up exactly with the sweep timeline.',
        technique: 'Alert correlation — order isolated sensor alerts into one timeline tied to the source range.',
        why: 'Turns scattered alerts into one coherent incident: a single coordinated reconnaissance sweep, evidence-backed for your report.' } },
  },
  topo: {
    nodes: {
      'perimeter': { x: 18, y: 54, glyph: '🧱', label: 'FW-LATAM', sub: 'perimeter firewall', type: '',
        intel: {
          what: 'The LATAM perimeter firewall whose logs tripped the alert — your starting point.',
          technique: 'Perimeter triage — verify the alert from the firewall\u2019s own denied-connection log, not the sensor summary alone.',
          why: 'Every investigation needs a confirmed entry point. From here you pivot outward to see how far the sweep reached.' } },
      'range': { x: 50, y: 46, glyph: '🛰', label: '203.0.113.0/24', sub: 'external source range', type: 'threat',
        intel: {
          what: 'The unknown external range sweeping services across the perimeter from many source addresses.',
          technique: 'Range analysis & WHOIS — identify the allocation, reputation, and breadth of ports the range touched.',
          why: 'Denied traffic can look like noise, but one range touching many services cannot be explained away. This is the core of the incident.' } },
      'svc': { x: 50, y: 84, glyph: '🔌', label: '27 perimeter services', sub: 'probed ports', type: 'threat',
        intel: {
          what: 'The 27 distinct services the range probed — far more than the perimeter actually exposes.',
          technique: 'Port-map comparison — tally the probed ports against the perimeter\u2019s real published services.',
          why: 'Probing services that are not exposed proves the source is mapping for openings, the hallmark of a discovery sweep.' } },
      'attacker': { x: 84, y: 22, glyph: '💀', label: 'flagged infra', sub: 'flagged by intel', type: 'threat',
        intel: {
          what: 'The reconnaissance infrastructure behind the source range, already flagged in 3 active threat-intel feeds.',
          technique: 'Reputation pivot — resolve the range to its hosting/reputation and check intel feeds.',
          why: 'Confirming hostile infrastructure justifies a perimeter-wide block and helps spot other campaigns from the same range.' } },
      'sensor': { x: 84, y: 70, glyph: '📡', label: 'SIEM sensors', sub: 'perimeter telemetry', type: '',
        intel: {
          what: 'The perimeter sensors and SIEM that recorded the sweep activity across FW-LATAM.',
          technique: 'Alert correlation — order the sensor alerts into one timeline tied to the source range.',
          why: 'The sensor record is your evidence trail — it proves the sweep happened and ties every probe to one range.' } },
    },
    links: [
      { a: 'perimeter', b: 'range',
        intel: {
          what: 'FW-LATAM received repeated denied probes from the external range.',
          technique: 'Firewall log review — group the denied connections by source prefix to surface the repeat offender.',
          why: 'This connection turns "noisy denies" into a confirmed external range probing the perimeter.' } },
      { a: 'range', b: 'svc',
        intel: {
          what: 'The range probed many distinct services in quick succession.',
          technique: 'Log analysis — list every distinct port the range touched.',
          why: 'Many services from one range is a sweep, not a session — the technical core of reconnaissance.' } },
      { a: 'range', b: 'attacker',
        intel: {
          what: 'The source range belongs to known scanning infrastructure.',
          technique: 'Reputation lookup — map the range to its intel classification.',
          why: 'Tying the range to flagged infrastructure justifies blocking it perimeter-wide.' } },
      { a: 'sensor', b: 'range', danger: true,
        intel: {
          what: 'SIEM sensors recorded the range\u2019s probes across the perimeter.',
          technique: 'Order the sensor alerts into one timeline keyed to the source range.',
          why: 'one range → many ports → whole perimeter: the recon sweep, corroborated end to end.' } },
    ],
  },
  tools: [
    { key: 'ls',   cmd: 'ls',                         unlock: 1, icon: '📁', name: 'List files', hint: 'ls' },
    { key: 'cat',  cmd: 'cat firewall.log',           unlock: 1, icon: '📄', name: 'Read firewall log', hint: 'cat <file>' },
    { key: 'grep', cmd: 'grep 203.0.113 firewall.log', unlock: 1, icon: '🔍', name: 'Find probes', hint: 'grep <pat> <file>' },

    { key: 'whois', cmd: 'whois 203.0.113.0/24', unlock: 2, icon: '🌐', name: 'WHOIS range', hint: 'whois <range>',
      run: { already: 'Already looked up — see the evidence board.', discover: 'unallocated-range', output: [
        { t: 'Range:     203.0.113.0/24' },
        { t: 'Status:    UNALLOCATED / Unregistered', c: 'warn' },
        { t: 'OrgName:   none on file   ·   abuse contact: none', c: 'warn' },
        { t: '[+] Anonymous, unallocated range — not a legitimate network.', c: 'ok' },
      ] } },
    { key: 'count', cmd: 'count ports', unlock: 2, icon: '🔢', name: 'Count probed ports', hint: 'count ports',
      run: { already: 'Already counted — see the evidence board.', discover: 'wide-footprint', output: [
        { t: 'distinct ports probed by 203.0.113.0/24:  27', c: 'warn' },
        { t: 'services the perimeter actually exposes:   3 (ssh, https, dns)' },
        { t: '[+] 27 ports vs 3 services — blind mapping of the attack surface.', c: 'warn' },
      ] } },
    { key: 'baseline', cmd: 'compare baseline', unlock: 2, icon: '📊', name: 'Compare baseline', hint: 'compare baseline',
      run: { already: 'Already compared — see the evidence board.', discover: 'not-approved-range', output: [
        { t: 'checking 203.0.113.0/24 against approved externals …', c: 'dim' },
        { t: '8.8.8.8         -> on baseline (Google DNS — benign)', c: '' },
        { t: '203.0.113.0/24  -> NOT on baseline', c: 'warn' },
        { t: '[+] The range is unauthorized; the Google resolver is ruled out.', c: 'ok' },
      ] } },

    { key: 'intel', cmd: 'intel 203.0.113.0/24', unlock: 3, icon: '⚲', name: 'Threat intel', hint: 'intel <range>',
      run: { already: 'Already checked — see the evidence board.', advanceTo: 4, addNode: 'attacker', discover: 'intel-flagged', output: [
        { t: '203.0.113.0/24  ->  threat-intel feeds', c: '' },
        { t: '  verdict: KNOWN scanning / reconnaissance infrastructure', c: 'warn' },
        { t: '  flagged in 3 active feeds this week', c: 'warn' },
      ] } },
    { key: 'scope', cmd: 'check perimeter', unlock: 3, icon: '👥', name: 'Check scope', hint: 'check perimeter',
      run: { already: 'Already checked — see the evidence board.', advanceTo: 4, addNode: 'svc', discover: 'multi-service-scope', output: [
        { t: 'querying perimeter for services touched by 203.0.113.0/24 …', c: 'dim' },
        { t: 'the range swept the full exposed service scope, not one port.', c: 'warn' },
        { t: '[+] This is a perimeter-wide sweep, not a single-service probe.', c: 'ok' },
      ] } },
    { key: 'correlate', cmd: 'correlate sweep', unlock: 3, icon: '🧭', name: 'Correlate sweep', hint: 'correlate sweep',
      run: { already: 'Already reviewed — see the evidence board.', advanceTo: 4, discover: 'sweep-pattern', output: [
        { t: 'correlating: one range · 27 ports · sequential · no real session', c: '' },
        { t: '[+] Signals match a textbook reconnaissance sweep.', c: 'ok' },
      ] } },
    { key: 'review', cmd: 'review alerts', unlock: 3, icon: '🚨', name: 'Review alerts', hint: 'review alerts',
      run: { already: 'Already reviewed — see the evidence board.', advanceTo: 4, addNode: 'sensor', discover: 'siem-corr', output: [
        { t: 'SIEM correlation:', c: 'head' },
        { t: '  burst of SYN probes from 203.0.113.0/24 across the perimeter' },
        { t: '  one range, sequential ports, sub-second spacing', c: 'warn' },
        { t: '[+] Sensor alerts confirm one coordinated sweep.', c: 'ok' },
      ] } },

    { key: 'block',   cmd: 'block range',      unlock: 5, icon: '⊘', name: 'Block range', hint: 'block range' },
    { key: 'harden',  cmd: 'harden perimeter', unlock: 5, icon: '🛡', name: 'Harden perimeter', hint: 'harden perimeter' },
    { key: 'monitor', cmd: 'raise monitoring', unlock: 5, icon: '📡', name: 'Raise monitoring', hint: 'raise monitoring' },
    { key: 'watch',   cmd: 'add watchlist',    unlock: 5, icon: '👁', name: 'Watchlist', hint: 'add watchlist' },
    { key: 'report',  cmd: 'submit report',    unlock: 5, icon: '📨', name: 'Submit report', hint: 'submit report' },
  ],
  verb: {
    whois: 'whois', count: 'count', compare: 'baseline',
    intel: 'intel', check: 'scope', correlate: 'correlate', review: 'review',
    block: 'block', harden: 'harden', raise: 'monitor', add: 'watch', submit: 'report',
  },
  doc: {
    ls:      { purpose: 'Lists every file in the folder you are currently in.',
               learn: 'Before you can investigate anything, you have to know what is in front of you. `ls` ("list") prints the contents of the perimeter log folder so you can spot the telemetry exported from the firewall.' },
    cat:     { purpose: 'Prints the full contents of a file to the screen.',
               learn: '`cat` reads a file out to the terminal. Point it at the firewall log to see every connection FW-LATAM denied — and which range keeps coming back.' },
    grep:    { purpose: 'Searches inside a file and shows only the matching lines.',
               learn: 'A sweep hides inside a noisy log. `grep` pulls out only the lines containing a pattern — point it at the suspect range in the firewall log to see every port it touched.' },
    whois:   { purpose: 'Looks up who owns an internet address range.',
               learn: 'Every legitimate network is allocated to an organisation with an abuse contact. `whois` reveals that ownership — or, for an attacker, the lack of it. An anonymous, unallocated range is a strong tell.' },
    count:   { purpose: 'Counts the distinct ports the range touched.',
               learn: 'A real peer connects to a service you actually offer. This tallies how many unique ports the range probed against the handful the perimeter truly exposes — probing 27 doors when 3 exist is blind discovery.' },
    baseline:{ purpose: 'Compares the range against the approved external list.',
               learn: 'A baseline is the reviewed list of externals the perimeter is supposed to talk to. Comparing against it turns "this looks unfamiliar" into "this is unauthorized" — and rules out benign peers like the Google DNS resolver.' },
    intel:   { purpose: 'Checks the range against threat-intelligence feeds.',
               learn: 'Other defenders share what they see. A reputation lookup tells you whether this range is already known as scanning infrastructure — independent proof you are not chasing a false positive.' },
    scope:   { purpose: 'Finds the full scope of services the range touched.',
               learn: 'One denied probe is rarely the whole story. Checking scope reveals how much of the exposed perimeter the same range swept — the real reach of the reconnaissance.' },
    correlate:{ purpose: 'Correlates the signals into a single verdict.',
               learn: 'Individual oddities are noise; together they tell a story. This stitches one-range-many-ports-sequential-no-session into the conclusion: a reconnaissance sweep.' },
    review:  { purpose: 'Reviews the related sensor alerts the SIEM raised.',
               learn: 'Your SIEM (the system watching everything) logged pieces of this sweep. Reviewing and ordering those alerts builds the timeline that corroborates your findings.' },
    block:   { purpose: 'Blocks the source range across the perimeter.',
               learn: 'Cutting off the range at the firewall stops it from probing further and from coming back for the openings it found. Removing the attacker\u2019s reach is the first move in containment.' },
    harden:  { purpose: 'Closes or restricts the exposed perimeter services.',
               learn: 'Reconnaissance maps your doors so an attacker can pick one later. Hardening the exposed perimeter shuts those doors before they can be used.' },
    monitor: { purpose: 'Raises monitoring on the perimeter.',
               learn: 'A sweep is often the prelude to an attack. Raising monitoring on the perimeter means you will catch the follow-up the moment it begins.' },
    watch:   { purpose: 'Adds the range to the watchlist for future sightings.',
               learn: 'Attackers reuse infrastructure. Adding the range to the watchlist means any future contact from it is flagged immediately, organisation-wide.' },
    report:  { purpose: 'Writes up and closes the incident.',
               learn: 'Every investigation ends with a record: what happened, what you found, and what you did. The report lets the whole team learn and proves the threat was handled.' },
  },
  hintFlow: {
    stage1: [
      { type: 'ran', key: 'ls', hint: 'ls' },
      { type: 'read', file: 'firewall.log', hint: 'cat' },
      { hint: 'grep' },
    ],
    stage2: { group: 'recon', need: 3, toolsHint: 'reconTools', pinHint: 'pinRecon' },
    stage3: { hint: 'socStart' },
    stage4: { group: 'soc', need: 3, toolsHint: 'socTools', pinHint: 'pinSoc' },
    stage5: { required: ['block', 'harden', 'monitor'], actHint: 'contain', reportHint: 'report' },
  },
  hints: {
    ls: { id: 'ls', tiers: [
      'Every investigation starts with orientation — get your bearings before you touch anything. You are in the perimeter logs exported from FW-LATAM.',
      'A log folder holds files, and you cannot reason about what you cannot see. Your first job is to find out which files are actually here.',
      'In Linux, one short two-letter command lists the files in the current folder.',
      'Type `ls` and press Enter to list the files.',
    ] },
    cat: { id: 'cat', tiers: [
      'A good analyst reads the raw evidence first-hand. One file is the firewall log — that is where the denied probes show themselves.',
      'You cannot tell who is knocking on the perimeter without seeing every connection it denied. Read the firewall log and look for a range that repeats.',
      "Use the command that prints a file's contents to the screen, followed by the firewall log's name.",
      'Type `cat firewall.log` to read the perimeter firewall log.',
    ] },
    grep: { id: 'grep', tiers: [
      'You have a suspect range now. The wording of a log can hide a pattern, but the ports it touched cannot — that contrast is the heart of this case.',
      'Separate the suspect from the noise: pull every line about that one range out of the firewall log so you can see exactly what it reached for.',
      'There is a Linux tool that prints only the lines of a file matching a pattern. Use it on the firewall log with the suspect range prefix.',
      'Type `grep 203.0.113 firewall.log` to surface its probes.',
    ] },
    reconTools: { id: 'reconTools', tiers: [
      'Your job now shifts from reading to proving. The proof is technical: who this range really is, how wide it probed, and that it was scanning, not connecting.',
      'Establish three things: who the range is allocated to, how many ports it touched versus what the perimeter exposes, and whether it is even an approved external.',
      'The dock now has a LOG ANALYSIS group. Each tool exposes a different tell — ownership, the probed-port count, and the baseline comparison. Work through them one at a time.',
      'Type `whois 203.0.113.0/24` first, then `count ports` and `compare baseline`.',
    ] },
    pinRecon: { id: 'pinRecon', tiers: [
      'Investigating surfaces evidence, but findings only count once recorded. An analyst builds a case from committed indicators, not loose observations.',
      'Indicators are appearing on the EVIDENCE board to the right — commit the ones that prove reconnaissance.',
      'Pin at least 3 indicators. You can click an evidence card, or use the pin command in the terminal.',
      'Type `pin all` to pin every indicator you have surfaced.',
    ] },
    socStart: { id: 'socStart', tiers: [
      'Zoom out. A sweep against one perimeter is rarely the whole story — find out whether intel already knows this range and how far it reached.',
      'Start with the range\u2019s reputation: confirm whether it is known scanning infrastructure before you map the rest.',
      'Use the SOC tools that just unlocked. Start by checking the range against threat intel.',
      'Type `intel 203.0.113.0/24` to begin the correlation.',
    ] },
    socTools: { id: 'socTools', tiers: [
      'Correlation is about scope: a sweep you only half-understand is one you cannot fully contain. Widen the lens from one probe to the whole perimeter.',
      'Map how much of the service surface was probed, confirm the pattern is really a sweep, and tie the SIEM\u2019s alerts to the range.',
      'The SOC CORRELATION group widens the lens — reputation, scope across services, the sweep pattern, and the SIEM timeline. Run each one.',
      'Try `check perimeter`, then `correlate sweep` and `review alerts`.',
    ] },
    pinSoc: { id: 'pinSoc', tiers: [
      'Before you are allowed to act, you have to justify it. Containment without recorded findings is a guess; recorded findings make it an authorized response.',
      'Record the correlation findings you just uncovered so your response is backed by evidence.',
      'Pin at least 3 of your SOC findings on the evidence board.',
      'Type `pin all` to pin your SOC findings.',
    ] },
    contain: { id: 'contain', tiers: [
      'Now you act — but order matters. Containment follows a logic: cut the range off, close the doors it found, then watch for the follow-up.',
      'Work through the response in that order: block the range, harden the exposed perimeter, then raise monitoring.',
      'The CONTAINMENT group holds your response actions — one blocks the range, one hardens the exposed perimeter, and one raises monitoring. Take them all.',
      'Type `block range`, `harden perimeter`, then `raise monitoring`.',
    ] },
    report: { id: 'report', tiers: [
      'An incident is not closed until it is documented. The written record is how the next analyst learns from what you did.',
      'Close out the investigation with a written incident report.',
      'Submit your incident report to finish the investigation.',
      'Type `submit report` to close the incident.',
    ] },
  },
  contain: {
    block:   { need: 'intel-flagged', label: 'block range',
               ok: '[+] 203.0.113.0/24 blocked at the perimeter — no further probes can reach FW-LATAM.',
               nodes: { range: 'blocked', attacker: 'blocked' } },
    harden:  { need: 'wide-footprint', label: 'harden perimeter',
               ok: '[+] Exposed perimeter services restricted to known peers; the probed doors are closed.',
               nodes: { perimeter: 'secured', svc: 'secured' } },
    monitor: { need: 'multi-service-scope', label: 'raise monitoring',
               ok: '[+] Heightened monitoring raised on the LATAM perimeter sensors.',
               nodes: { sensor: 'cleared' } },
    watch:   { need: 'intel-flagged', label: 'add watchlist',
               ok: '[+] 203.0.113.0/24 added to the org-wide watchlist for future sightings.',
               nodes: { attacker: 'blocked' } },
  },
  containRequired: ['block', 'harden', 'monitor'],
  reveal: {
    campaign: [
      { t: '' },
      { t: '── PATTERN DETECTED ──────────────────────────────', c: 'head' },
      { t: 'This is not a handful of stray denies. One external range is sweeping', c: 'warn' },
      { t: 'services across the LATAM perimeter — active RECONNAISSANCE against CyberCorp.', c: 'warn' },
      { t: 'A perimeter map is opening above the terminal — it will grow as you uncover', c: 'dim' },
      { t: 'more. Check the range against threat intel to confirm the infrastructure.', c: 'dim' },
    ],
    containment: [
      { t: '' },
      { t: '── CONTAINMENT AUTHORIZED ────────────────────────', c: 'head' },
      { t: 'Enough evidence is pinned to act. Containment tools are now unlocked.', c: 'ok' },
      { t: 'Each action changes the perimeter map. When it\u2019s contained, file your incident report to close out.', c: 'dim' },
    ],
  },
  reportDone: [{ t: '[+] Incident report submitted. Reconnaissance sweep contained.', c: 'ok' }],
  scorecard: {
    title: 'Reconnaissance sweep contained',
    subLead: 'You started at a Linux terminal with one flagged firewall and worked all the way to a perimeter-wide block — pinning ',
    subMid: ' indicators and taking ',
    subTail: ' response actions.',
    evHead: 'Reconnaissance indicators you identified',
    socHead: 'SOC correlation you performed',
    learned: [
      'A perimeter firewall log is an artifact you can inspect from a terminal — <code>ls</code>, <code>cat</code> and <code>grep</code> surface the evidence.',
      'A sweep is proven by the <em>pattern</em> — one range across many ports and services — not by any single denied packet.',
      'A baseline and <code>whois</code> turn "unfamiliar" into "unauthorized"; the benign Google DNS resolver (8.8.8.8) is ruled out the same way.',
      'Containment is a sequence: block the range, harden the exposed perimeter, raise monitoring, report.',
    ],
  },
};
