/*
 * lab.missions/mission-000b.js — CyberCorp Analyst Orientation 2 (Warm-up #2)
 *
 * The SECOND beginner network/SOC orientation lab. Like Assignment 000 it is a
 * warm-up, NOT a graded assignment: reachable ONLY via the deep link
 * `?lab=mission-000b`, intentionally absent from MISSION_PLAY_ORDER / the mission
 * list / the Operations Center map / the unlock chain. It awards NO XP and never
 * persists — the host's notifyLabComplete() no-ops for ids outside
 * MISSION_PLAY_ORDER, and the host's canOpen() bypass covers the orientation ids.
 *
 * It reuses the SAME generic lab engine (lab.js) as mission-000 — every engine
 * path (orientation map, guided tutorial, multiple-choice report, scorecard) is
 * data-gated off `report.choices`, so this file is a structural twin of
 * mission-000 with a fresh case: a different host, a different unknown source,
 * and a different set of probed ports. The investigative LOOP is identical on
 * purpose — repetition with variation is how a beginner builds the instinct.
 *
 * Flow (the same short, guided arc as Orientation 1):
 *   1. TRIAGE   — read the connection snapshot, find the repeated outside address
 *   2. ANALYSIS — pin the two things you observed (unlocks the analyst tools)
 *   3. IDENTIFY — whois / ports / baseline confirm the source, then file a
 *                 MULTIPLE-CHOICE orientation report and read a short debrief.
 *
 * Response actions (block / isolate / escalate) are shown but LOCKED.
 *
 * Scenario: one unknown external host (192.0.2.55) contacting FIN-3310
 * (10.0.8.30) across several unrelated ports; a benign CDN (198.51.100.20) and
 * internal DNS act as known-good contrast.
 */
export default {
  id: 'mission-000b',
  opId: 'OPS-TRN-001',
  severity: 'TRAINING',
  headerTitle: 'Analyst Orientation 2 — Confirming an Unknown Source',
  context: 'Training Telemetry · Host: FIN-3310',
  consoleAriaLabel: 'Analyst Orientation 2 — Confirming an Unknown Source',
  mapCap: 'NETWORK MAP — builds as you investigate',
  nodeTags: { blocked: 'BLOCKED', cleared: 'WATCHED', secured: 'SECURED' },
  reportKey: 'report',
  seedNodes: ['workstation', 'source'],
  groups: {
    dock: { 1: 'TRIAGE', 3: 'ANALYST TOOLS', 5: 'RESPONSE ACTIONS' },
    kit:  { 1: 'TRIAGE COMMANDS', 3: 'ANALYST TOOLS', 5: 'RESPONSE ACTIONS' },
  },
  prompts: {
    threshold: 3,
    fileLabel: 'trainee@fin-3310: ~/triage',
    filePrompt: 'trainee@fin-3310:~/triage$',
    filePwd: '/home/trainee/triage',
    socLabel: 'trainee@soc — orientation OPS-TRN-001',
    socPrompt: 'trainee@soc:~$',
    socPwd: '/home/trainee',
  },
  intro: [
    { t: 'CyberCorp Security Training — Assignment 000b · Analyst Orientation 2', c: 'head' },
    { t: 'Welcome back. This is your second warm-up — same SOC loop, a brand new case. You already know the rhythm; this time you drive it on different evidence.' },
    { t: 'A finance workstation (FIN-3310) has been flagged. Your job is the same:', c: 'dim' },
    { t: 'read the connection snapshot, find the outside address that keeps coming', c: 'dim' },
    { t: 'back, check who it is, and decide whether it is worth escalating.', c: 'dim' },
    { t: 'Everything is still explained as you reach it. Follow the GUIDED TUTORIAL', c: 'dim' },
    { t: 'on the left — the exact command to run, why you are running it, and what', c: 'dim' },
    { t: 'each result means. Investigate first, decide last.', c: 'dim' },
  ],
  support: { beginner: true },
  objective: {
    1: 'Open the connection snapshot for FIN-3310 and find which outside address keeps coming back.',
    2: 'Commit what you observed — pin the two indicators to your evidence board (2 to continue).',
    3: 'Identify the source: run your analyst tools (who owns it, which ports, is it on the baseline), then file your orientation report.',
  },
  framing: {
    1: { suspicion: 'Sensors flagged repeated traffic to FIN-3310 from one outside address.',
         question: 'Which external address keeps coming back to this workstation?',
         why: 'Repeated contact from one unknown source is the very first thing a SOC analyst checks.' },
    2: { suspicion: 'The same outside address shows up again and again, on several ports.',
         question: 'Is this a normal peer, or something worth a closer look?',
         why: 'Committing what you observe turns a hunch into evidence you can act on.' },
    3: { suspicion: 'One unknown external source touched multiple services on the workstation.',
         question: 'Who owns it, which ports did it hit, and is it an approved peer?',
         why: 'Confirming the source and comparing it to the baseline is how you decide if traffic is suspicious.' },
  },
  socStages: [
    { key: 'triage',      label: 'Triage',             question: 'What looks unusual?',
      note: 'Inspect and search the exported evidence with Linux-style commands.',
      sub: ['Review the connection snapshot & logs', 'Find the address that keeps coming back'] },
    { key: 'analysis',    label: 'SOC Tool Analysis',  question: 'Does the evidence support the suspicion?',
      note: 'Validate the suspicion with SOC analyst tools — ownership, ports, baseline.',
      sub: ['Run WHOIS, ports & baseline checks', 'Confirm who owns it and what it touched'] },
    { key: 'correlation', label: 'Correlation',        question: 'How do the clues connect?',
      note: 'Connect the separate clues into one analyst conclusion.',
      sub: ['Stack the separate indicators together', 'See the pattern they form'] },
    { key: 'escalation',  label: 'Escalation',         question: 'Do I have enough confidence?',
      note: 'Decide whether the evidence is strong enough to escalate.',
      sub: ['Judge if confidence is high enough', 'Choose the proportionate action'] },
    { key: 'response',    label: 'Response',           question: 'What operational action changes?',
      note: 'See the consequence your escalation set in motion.',
      sub: ['Watch the consequence of escalating', 'Confirm nothing was over-blocked'] },
    { key: 'debrief',     label: 'Debrief',            question: 'What did we learn?',
      note: 'Turn the investigation into retained learning.',
      sub: ['Capture what the investigation taught', 'Lock in the core triage loop'] },
  ],
  mission: {
    summary: 'Investigate suspicious activity targeting workstation FIN-3310 and decide whether it is worth escalating.',
    host: 'FIN-3310 · 10.0.8.30',
    role: 'Tier-1 SOC Analyst · Orientation 2',
  },
  tips: 'Same loop as last time — investigate first, decide last. Read each result before moving on; every command answers one small question.',
  alertFeed: {
    start:     [{ sev: 'warn', text: 'Sensor flagged repeated inbound contact to FIN-3310 from an outside address.' }],
    cat:       [{ sev: 'info', text: 'Connection snapshot opened — several active connections; one repeated outside address still unidentified.' }],
    grep:      [{ sev: 'warn', text: '192.0.2.55 touched ssh, smb, rdp & mssql — multi-service probing.' }],
    whois:     [{ sev: 'high', text: 'WHOIS: 192.0.2.55 has no registered owner and no abuse contact.' }],
    ports:     [{ sev: 'warn', text: 'Port map: source reached services FIN-3310 does not even run.' }],
    baseline:  [{ sev: 'warn', text: 'Baseline check: 192.0.2.55 is NOT on the known-good peer list.' }],
    correlate: [{ sev: 'high', text: 'Correlation: unknown source + unrelated ports + off-baseline = recon.' }],
    escalate:  [{ sev: 'high', text: 'Case escalated to tier-2 · FIN-3310 monitored · source watchlisted.' }],
  },
  analystNotes: {
    cat:       'One repeated outside address keeps reappearing — identity not yet resolved.',
    grep:      'Suspect touched four unrelated services — looks like probing, not normal use.',
    whois:     'Source is anonymous infrastructure — no registered owner, no abuse contact.',
    ports:     'Source reached ports this host does not run — the shape of blind probing.',
    baseline:  'Source is off-baseline; the CDN and DNS beside it are known-good.',
    correlate: 'The clues stack into one pattern — recommending escalation.',
  },
  observedBehavior: [
    { key: 'repeat', label: 'Repeated attempts' },
    { key: 'ports',  label: 'Multiple ports' },
    { key: 'owner',  label: 'Unknown ownership' },
    { key: 'base',   label: 'Off-baseline' },
  ],
  tutorial: [
    { key: 'ls', toolKey: 'ls', stage: 'triage', label: 'See what you\u2019re working with',
      say: 'List the files pulled off the flagged workstation so you know what evidence you have to work through.',
      result: 'Four files of telemetry from FIN-3310 — the connection snapshot, the access log, the known-good baseline, and your notes.' },
    { key: 'cat', toolKey: 'cat', stage: 'triage', label: 'Read the connection snapshot',
      say: 'Open the live connection snapshot to see every address FIN-3310 is currently talking to.',
      result: 'One outside address — 192.0.2.55 — keeps coming back, across four different ports.' },
    { key: 'grep', toolKey: 'grep', stage: 'triage', label: 'Pull the suspect out of the log',
      say: 'Search the access log for that one address to see exactly which services it reached for.',
      result: 'It touched ssh, smb, rdp and mssql — one host poking many doors is probing, not normal use.' },
    { key: 'pin', cmd: 'pin all', stage: 'triage', label: 'Save what you found',
      say: 'Commit both observations to your evidence board so your findings are on the record.',
      result: 'Both observations are pinned — the analyst tools unlock so you can confirm what you found.' },
    { key: 'whois', toolKey: 'whois', stage: 'analysis', label: 'Look up who owns the source',
      say: 'These next tools are SOC analyst tools, not basic Linux commands. Start by checking who the outside address is registered to.',
      result: 'No registered owner and no abuse contact — anonymous infrastructure, not an accountable peer.' },
    { key: 'ports', toolKey: 'ports', stage: 'analysis', label: 'See which ports it hit',
      say: 'Map the ports the source reached against the ones this host actually runs.',
      result: 'It reached for services FIN-3310 doesn\u2019t even run — the shape of blind probing.' },
    { key: 'baseline', toolKey: 'baseline', stage: 'analysis', label: 'Compare to known-good peers',
      say: 'Check the source against the reviewed list of peers FIN-3310 is approved to talk to.',
      result: 'It\u2019s not on the baseline — so it\u2019s unexpected, while the CDN and DNS beside it are ruled out.' },
    { key: 'correlate', stage: 'correlation', label: 'Connect the clues',
      say: 'No single clue is enough on its own. Read how they fit together, then move to your decision.',
      result: 'Repeated unknown source + unrelated ports + no registered owner + off-baseline — together, a pattern worth escalating.' },
    { key: 'report', toolKey: 'report', stage: 'escalation', label: 'Make your escalation decision',
      say: 'You have enough to decide. Open the escalation decision, then pick the action your evidence best supports.',
      result: 'Decision made — escalated as suspicious reconnaissance.' },
  ],
  correlation: {
    head: 'CORRELATION — connect the clues',
    intro: 'One clue is never enough. An analyst builds confidence by stacking them:',
    clues: [
      'One unknown outside address kept coming back.',
      'It reached several unrelated ports/services at once.',
      'WHOIS shows no registered owner — anonymous infrastructure.',
      'It is not on the host\u2019s known-good baseline.',
    ],
    contrast: 'For contrast: the CDN (198.51.100.20) and internal DNS (10.0.8.1) ARE on the baseline — known-good, and ruled out. Not all external traffic is bad.',
    summary: 'Multiple unrelated ports alone is not enough. Unknown ownership alone is not enough. Off-baseline alone is not enough. Together, they form a pattern worth escalating.',
    ack: 'I see the pattern \u2014 continue',
  },
  files: [
    { name: 'README.txt', icon: '📘', desc: 'orientation notes' },
    { name: 'network_snapshot.txt', icon: '🗂', desc: 'live connection snapshot', suspect: true },
    { name: 'access.log', icon: '📄', desc: 'service access log' },
    { name: 'baseline.txt', icon: '📊', desc: 'known-good peers' },
  ],
  fs: {
    'README.txt': [
      'Analyst Orientation 2 — confirming an unknown source',
      '',
      'Welcome back. Same vocabulary as last time, in case you need it:',
      '',
      '  IP address  an address for a device on the network (e.g. 10.0.8.30).',
      '              10.x addresses are usually internal (ours); other ranges',
      '              are outside / the wider internet.',
      '  Port        a numbered "door" for one service: 22=ssh, 445=smb,',
      '              3389=rdp, 1433=database. A normal peer uses one or two.',
      '  Baseline    the reviewed list of contacts a host is SUPPOSED to talk to.',
      '',
      'Workstation FIN-3310 (10.0.8.30) was flagged. Walk through it:',
      '  1. list the files in this triage folder',
      '  2. read the connection snapshot and find the outside address that repeats',
      '  3. pull that address out of the access log to see which ports it touched',
      '',
      'Investigate first, decide last. Press HINT any time, or open the SOC TOOL',
      'KIT for the exact commands.',
    ],
    'network_snapshot.txt': [
      'FIN-3310 active connections (snapshot)',
      '',
      'PROTO  LOCAL            REMOTE              STATE',
      'tcp    10.0.8.30:52310  192.0.2.55:445      ESTABLISHED',
      'tcp    10.0.8.30:52312  192.0.2.55:22       TIME_WAIT',
      'tcp    10.0.8.30:52314  192.0.2.55:3389     SYN_SENT',
      'tcp    10.0.8.30:52316  192.0.2.55:1433     SYN_SENT',
      'tcp    10.0.8.30:50640  198.51.100.20:443   ESTABLISHED   (CDN)',
      'tcp    10.0.8.30:50642  10.0.8.1:53         ESTABLISHED   (DNS)',
      '',
      'Reminder: 10.x addresses are internal. 192.0.2.55 is an outside address —',
      'and it appears on four different ports.',
    ],
    'access.log': [
      '# service access log (most recent first)',
      '192.0.2.55 -> port 22 (ssh)      probe',
      '192.0.2.55 -> port 445 (smb)     probe',
      '192.0.2.55 -> port 3389 (rdp)    probe',
      '192.0.2.55 -> port 1433 (mssql)  probe',
      '198.51.100.20 -> port 443 (https) content fetch (CDN)',
      '10.0.8.40 -> port 445 (smb)       normal file share',
    ],
    'baseline.txt': [
      'FIN-3310 known-good peers (reviewed baseline)',
      '',
      '  10.0.8.1        internal DNS resolver',
      '  10.0.8.40       department file server',
      '  198.51.100.20   content delivery network (software updates)',
      '',
      'Anything contacting this host that is NOT on this list is "unexpected"',
      'until proven otherwise. 192.0.2.55 is not here.',
    ],
  },
  fileInvestigation: {
    helpHead: 'Triage commands — investigate the exported telemetry:',
    filesHead: '📂 ~/triage &nbsp; <span>—</span> &nbsp; click a file to <code>cat</code> it',
    railEmpty: 'No evidence yet. Read the files, then pin the indicators you find.',
    onCat: {
      'network_snapshot.txt': {
        note: [{ t: '[!] One outside address — 192.0.2.55 — appears on four different ports. That repetition is worth a closer look.', c: 'warn' }],
        discover: 'repeat-external',
        next: [{ t: 'Next, pull that address out of the access log to see exactly which ports it touched.', c: 'dim' }],
      },
    },
    grepAha: {
      file: 'access.log',
      requireUrl: false,
      found: [
        { t: '[+] 192.0.2.55 reached for ssh, smb, rdp AND mssql — four', c: 'ok' },
        { t: '    different services from one outside address. A real peer talks', c: 'ok' },
        { t: '    to one service; touching many at once is probing behaviour.', c: 'ok' },
      ],
      fb: {
        means: 'One outside address — 192.0.2.55 — touched ssh, smb, rdp and mssql; a normal peer uses a single service.',
        changes: 'This is no longer just "odd traffic" — you have an unknown source reaching for many unrelated services.',
        next: 'Who owns that address, and is it an approved peer for this host?',
      },
      discover: 'multi-port-probe',
      advanceTo: 2,
      unlock: [
        { t: '' },
        { t: '── OBSERVATIONS READY ────────────────────────────', c: 'head' },
        { t: 'You spotted the two key things. Now COMMIT them: pin each indicator', c: 'dim' },
        { t: 'on the EVIDENCE board so your findings are on the record.', c: 'dim' },
      ],
    },
  },
  ind: {
    'repeat-external': { group: 'recon', kind: 'TRAFFIC', label: 'One outside address keeps contacting FIN-3310',
      teach: '192.0.2.55 appears again and again in the snapshot. A legitimate peer usually uses one service; one unknown address reappearing is the first thing to check.',
      intel: {
        what: 'A single external address (192.0.2.55) connecting to FIN-3310 over and over, across multiple ports.',
        technique: 'Connection review — read the live snapshot and look for one remote address that keeps reappearing.',
        why: 'Repeated contact from one outside source is the cheapest, earliest signal that something is off.',
        supports: 'An unknown source worth investigating.' } },
    'multi-port-probe': { group: 'recon', kind: 'SCAN', label: 'That address touched several different ports',
      teach: 'The same host reached ssh (22), smb (445), rdp (3389) and mssql (1433). Touching many unrelated services at once looks like probing, not normal use.',
      intel: {
        what: '192.0.2.55 reached for ssh, smb, rdp and mssql in quick succession.',
        technique: 'Log analysis — grep the access log for the suspect address and list every port it touched.',
        why: 'A real connection uses one service; reaching many different ports is the shape of a scan.',
        supports: 'Probing behaviour, not a normal single-service peer.' } },
    'unknown-source': { group: 'soc', kind: 'WHOIS', label: 'The source is unregistered / unknown infrastructure',
      teach: 'WHOIS on 192.0.2.55 returns no organisation and no abuse contact — anonymous infrastructure, unlike the named CDN it sits next to.',
      intel: {
        what: '192.0.2.55 resolves to no registered organisation and lists no abuse contact.',
        technique: 'WHOIS lookup — query the registry for ownership and abuse contact of the source IP.',
        why: 'Legitimate services are registered and contactable; anonymous infrastructure is a red flag.',
        supports: 'An unknown source, not an accountable peer.' } },
    'targeted-ports': { group: 'soc', kind: 'PORTS', label: 'It probed multiple unrelated services (22/445/3389/1433)',
      teach: 'FIN-3310 only listens on ssh and smb, yet the source hit rdp and mssql too. It is reaching for doors this host does not even have.',
      intel: {
        what: 'The probed ports (3389/1433) include services FIN-3310 does not run at all.',
        technique: 'Port comparison — line up the probed ports against what the host actually listens on.',
        why: 'Reaching for services that do not exist is blind probing, not a real connection.',
        supports: 'Multiple unrelated ports — blind probing.' } },
    'off-baseline': { group: 'soc', kind: 'BASELINE', label: 'The source is not on the known-good baseline',
      teach: '192.0.2.55 is absent from the reviewed list of approved peers — and the CDN beside it is on the list. The baseline turns "looks odd" into "is unexpected".',
      intel: {
        what: '192.0.2.55 does not appear on FIN-3310\u2019s reviewed list of known-good peers.',
        technique: 'Baseline comparison — diff the observed contacts against the approved peer list.',
        why: 'The baseline is what lets you call a source unexpected rather than merely unfamiliar.',
        supports: 'Off-baseline — unexpected, not a known-good peer.' } },
  },
  topo: {
    zones: [
      { id: 'internal-user', label: 'Internal User',           x: 1,  w: 23 },
      { id: 'internal-svc',  label: 'Internal Services',        x: 25, w: 23 },
      { id: 'external',      label: 'External Internet',        x: 52, w: 22 },
      { id: 'suspicious',    label: 'Suspicious / Unverified',  x: 76, w: 23 },
    ],
    nodes: {
      'workstation': { x: 14, y: 40, zone: 'internal-user', glyph: '💻',
        label: 'FIN-3310', sysType: 'Finance Workstation', ip: '10.0.8.30', baseTrust: 'internal',
        intel: {
          what: 'The finance workstation that was flagged — your starting point.',
          technique: 'Endpoint triage — review the connection and log data exported from this host.',
          why: 'Everything you analyse is traffic to or from this host.' },
        inspect: {
          means: 'An employee\u2019s computer — the host this whole investigation is about.',
          care: 'Analysts check whether outside systems are talking to it in expected ways.',
          next: 'Which outside addresses is it talking to, and are they expected?' } },
      'dns': { x: 37, y: 22, zone: 'internal-svc', glyph: '🧭',
        label: 'Internal DNS', sysType: 'Name resolution', ip: '10.0.8.1', baseTrust: 'service',
        intel: {
          what: 'The internal DNS server the workstation uses to look up addresses.',
          technique: 'Baseline comparison.',
          why: 'A normal, expected internal peer — a picture of healthy traffic.' },
        inspect: {
          means: 'The internal server that turns names into addresses for the workstation.',
          care: 'Internal DNS traffic is routine — it shows what normal looks like.',
          next: 'Does this match the known-good baseline of expected peers?' } },
      'fileserver': { x: 37, y: 50, zone: 'internal-svc', glyph: '🗂️',
        label: 'File Server', sysType: 'Internal file share', ip: '10.0.8.40', baseTrust: 'service',
        intel: {
          what: 'An internal file server the workstation talks to over SMB.',
          technique: 'Baseline comparison.',
          why: 'A normal, expected internal peer — part of the known-good picture.' },
        inspect: {
          means: 'The internal server that stores shared department files.',
          care: 'Routine file-share traffic is expected — it is on the baseline.',
          next: 'Confirm it is known-good, then rule it out.' } },
      'ws2': { x: 14, y: 72, zone: 'internal-user', glyph: '💻',
        label: 'FIN-3311', sysType: 'Finance Workstation', ip: '10.0.8.31', baseTrust: 'internal',
        intel: {
          what: 'A neighbouring employee workstation on the same internal segment.',
          technique: 'Baseline comparison.',
          why: 'A second normal host — a picture of healthy internal activity for contrast.' },
        inspect: {
          means: 'Another employee computer on the same internal network as FIN-3310.',
          care: 'Its traffic is routine — a baseline for what normal looks like.',
          next: 'Nothing to chase here — compare it against the flagged host.' } },
      'identity': { x: 37, y: 78, zone: 'internal-svc', glyph: '🔑',
        label: 'Identity Service', sysType: 'Single sign-on / auth', ip: '10.0.8.8', baseTrust: 'service',
        intel: {
          what: 'The internal identity / single-sign-on service the workstations authenticate against.',
          technique: 'Baseline comparison.',
          why: 'Expected internal auth traffic — part of the known-good picture.' },
        inspect: {
          means: 'The internal service that signs employees in across the network.',
          care: 'Routine auth traffic is expected — it is on the baseline.',
          next: 'Confirm it is known-good, then rule it out.' } },
      'update': { x: 63, y: 50, zone: 'external', glyph: '⬇️',
        label: 'Software Update Vendor', sysType: 'Patch / update service', ip: '198.51.100.42', baseTrust: 'external',
        intel: {
          what: 'An approved external software-update vendor internal services pull patches from.',
          technique: 'Baseline comparison.',
          why: 'External but approved — known-good once matched to the baseline.' },
        inspect: {
          means: 'An approved external vendor that internal services download software updates from.',
          care: 'External traffic is not automatically bad — approved vendors are benign.',
          next: 'Check it against the baseline (it is approved).' } },
      'microsoft': { x: 63, y: 74, zone: 'external', glyph: '☁️',
        label: 'Microsoft Services', sysType: 'Cloud productivity', ip: '52.96.0.10', baseTrust: 'external',
        intel: {
          what: 'Approved external Microsoft cloud services (mail / productivity) used from inside the network.',
          technique: 'Baseline comparison.',
          why: 'Expected external SaaS traffic — approved and benign.' },
        inspect: {
          means: 'Approved external Microsoft cloud services reached from inside the network.',
          care: 'Well-known approved SaaS — benign external traffic.',
          next: 'Confirm on the baseline and rule it out.' } },
      'cdn': { x: 63, y: 22, zone: 'external', glyph: '🌐',
        label: 'CDN', sysType: 'Content delivery', ip: '198.51.100.20', baseTrust: 'external',
        intel: {
          what: 'A public content-delivery network the workstation fetches assets from.',
          technique: 'Baseline comparison.',
          why: 'External but expected — on the known-good list, so ruled out as benign.' },
        inspect: {
          means: 'A public content network the workstation fetches assets and updates from.',
          care: 'External isn\u2019t automatically bad — if it matches baseline it\u2019s benign.',
          next: 'Is this CDN on the known-good baseline? (It is.)' } },
      'source': { x: 86, y: 24, zone: 'suspicious', glyph: '❓',
        label: 'Unknown Host', sysType: 'Unverified external', ip: '192.0.2.55', baseTrust: 'unknown',
        intel: {
          what: 'An unregistered outside address contacting the workstation repeatedly.',
          technique: 'WHOIS, port and baseline checks on the repeated source address.',
          why: 'Unknown, unaccountable infrastructure reaching many ports is a classic red flag.',
          supports: 'An unknown, off-baseline source.' },
        inspect: {
          means: 'An unregistered outside address contacting the workstation repeatedly.',
          care: 'Unknown infrastructure has to be validated — owner, ports, baseline.',
          next: 'Who owns it, which ports did it hit, and is it on the baseline?' } },
    },
    links: [
      { a: 'workstation', b: 'dns', traffic: 'normal',
        intel: {
          what: 'Routine name-resolution traffic to the internal DNS.',
          technique: 'Connection snapshot review.',
          why: 'A baseline of what normal internal traffic looks like.' },
        inspect: {
          means: 'Normal two-way name-resolution traffic.',
          care: 'Workstations query DNS and get answers — expected back-and-forth.',
          next: 'Use this as your picture of healthy internal traffic.' } },
      { a: 'workstation', b: 'fileserver', traffic: 'normal',
        intel: {
          what: 'Normal internal file-share traffic.',
          technique: 'Connection snapshot review.',
          why: 'Another example of expected, healthy internal contact.' },
        inspect: {
          means: 'Normal two-way internal file-share traffic.',
          care: 'Expected internal contact — a request and a response.',
          next: 'Confirm it\u2019s on the baseline, then rule it out.' } },
      { a: 'workstation', b: 'cdn', traffic: 'benign',
        intel: {
          what: 'Expected external traffic to a content-delivery network.',
          technique: 'Baseline comparison.',
          why: 'External but approved — benign outside traffic, shown for contrast.' },
        inspect: {
          means: 'Two-way traffic to a content-delivery network.',
          care: 'Likely normal external traffic if the CDN is on the baseline.',
          next: 'Check the baseline before ruling it in or out.' } },
      { a: 'workstation', b: 'source', traffic: 'suspicious', danger: true,
        intel: {
          what: 'Repeated contact between the host and an unknown outside address.',
          technique: 'Connection snapshot review, then WHOIS / ports / baseline.',
          why: 'This is the relationship the whole investigation turns on.',
          supports: 'An unknown source contacting the host.' },
        inspect: {
          means: 'Repeated one-way contact from an unknown address toward the workstation.',
          care: 'One-way or repeated probing can mean scanning — it must be verified.',
          next: 'Check ownership, ports touched, and the baseline.' } },
      { a: 'workstation', b: 'identity', traffic: 'normal',
        intel: {
          what: 'Normal two-way single-sign-on traffic.',
          technique: 'Connection snapshot review.',
          why: 'Workstations authenticate against identity — expected back-and-forth.' },
        inspect: {
          means: 'Normal two-way single-sign-on traffic.',
          care: 'Workstations authenticate against identity — expected back-and-forth.',
          next: 'Another picture of healthy internal traffic.' } },
      { a: 'fileserver', b: 'update', traffic: 'benign',
        intel: {
          what: 'Two-way traffic to an approved software-update vendor.',
          technique: 'Baseline comparison.',
          why: 'Approved external updates are benign if on the baseline.' },
        inspect: {
          means: 'Two-way traffic to an approved software-update vendor.',
          care: 'Approved external updates are benign if on the baseline.',
          next: 'Check the baseline before ruling it in or out.' } },
      { a: 'identity', b: 'microsoft', traffic: 'benign',
        intel: {
          what: 'Two-way traffic to Microsoft cloud services.',
          technique: 'Baseline comparison.',
          why: 'Well-known approved SaaS — benign external traffic.' },
        inspect: {
          means: 'Two-way traffic to Microsoft cloud services.',
          care: 'Well-known approved SaaS — benign external traffic.',
          next: 'Confirm on the baseline, then rule it out.' } },
      { a: 'ws2', b: 'identity', traffic: 'normal',
        intel: {
          what: 'A neighbouring workstation authenticating normally.',
          technique: 'Connection snapshot review.',
          why: 'Routine internal auth — healthy background traffic.' },
        inspect: {
          means: 'A neighbouring workstation authenticating normally.',
          care: 'Routine internal auth — healthy background traffic.',
          next: 'Nothing to chase — a baseline of normal.' } },
    ],
    mapReact: {
      start:     { reveal: ['workstation', 'dns'], mask: ['source'], zones: ['internal-user', 'internal-svc'],
                   trust: { workstation: 'internal', dns: 'service' } },
      cat:       { reveal: ['fileserver'], trust: { fileserver: 'service' } },
      grep:      { unmask: ['source'], zones: ['suspicious'], emphasizeSuspect: true,
                   trust: { source: 'unverified' } },
      whois:     { trust: { source: 'offbaseline' } },
      ports:     { ports: true },
      baseline:  { reveal: ['cdn', 'identity', 'update', 'microsoft', 'ws2'], zones: ['external'],
                   trust: { dns: 'knowngood', fileserver: 'knowngood', identity: 'knowngood', cdn: 'knowngood', update: 'knowngood', microsoft: 'knowngood', ws2: 'internal', source: 'offbaseline' } },
      correlate: { trust: { source: 'suspicious' } },
      escalate:  { escalated: true, trust: { source: 'watched', workstation: 'monitored' } },
    },
    maskedNode: {
      glyph: '📡',
      label: 'Unresolved Activity',
      sysType: 'External \u2014 not yet identified',
      trustLabel: 'Unresolved \u2014 investigate',
      inspect: {
        means: 'Unidentified external activity reaching FIN-3310 \u2014 not yet resolved.',
        care: 'Something outside is making contact, but its identity is still unknown.',
        next: 'Pull the repeated outside address out of the access log to identify it.',
      },
    },
  },
  tools: [
    { key: 'ls',   cmd: 'ls',                            unlock: 1, icon: '📁', name: 'List files',   hint: 'ls' },
    { key: 'cat',  cmd: 'cat network_snapshot.txt',      unlock: 1, icon: '📄', name: 'Read snapshot', hint: 'cat <file>' },
    { key: 'grep', cmd: 'grep 192.0.2.55 access.log',    unlock: 1, icon: '🔍', name: 'Find the source', hint: 'grep <pat> <file>' },

    { key: 'whois', cmd: 'whois 192.0.2.55', unlock: 3, icon: '🌐', name: 'WHOIS source', hint: 'whois <ip>',
      run: { already: 'Already looked up — see the evidence board.', discover: 'unknown-source', output: [
        { t: 'IP:        192.0.2.55' },
        { t: 'OrgName:   Unknown / Unregistered', c: 'warn' },
        { t: 'Country:   --   ·   abuse contact: none on file', c: 'warn' },
        { t: '[+] Anonymous, unregistered source — not a known, accountable peer.', c: 'ok' },
      ], fb: {
        means: 'The source address resolves to no registered organisation and lists no abuse contact.',
        changes: 'This is unknown infrastructure, not a legitimate peer that merely looked unfamiliar.',
        next: 'Which ports did it actually reach — and does this host even run them?',
      } } },
    { key: 'ports', cmd: 'ports 192.0.2.55', unlock: 3, icon: '🚪', name: 'Probed ports', hint: 'ports <ip>',
      run: { already: 'Already mapped — see the evidence board.', discover: 'targeted-ports', output: [
        { t: 'ports reached by 192.0.2.55:  22, 445, 3389, 1433' },
        { t: 'FIN-3310 actually listens on:  22 (ssh), 445 (smb)' },
        { t: '[+] 3389/1433 are services this host does not even run — blind probing.', c: 'warn' },
      ], fb: {
        means: 'The source reached for 3389 and 1433 — services FIN-3310 does not run.',
        changes: 'Reaching for doors that do not exist is probing, not a real connection.',
        next: 'Is this address on the host\u2019s approved peer list, or is it unexpected?',
      } } },
    { key: 'baseline', cmd: 'compare baseline', unlock: 3, icon: '📊', name: 'Compare baseline', hint: 'compare baseline',
      run: { already: 'Already compared — see the evidence board.', discover: 'off-baseline', output: [
        { t: 'checking 192.0.2.55 against known-good peers …', c: 'dim' },
        { t: '198.51.100.20  -> on baseline (CDN — benign)', c: '' },
        { t: '10.0.8.1       -> on baseline (internal DNS — benign)', c: '' },
        { t: '192.0.2.55     -> NOT on baseline', c: 'warn' },
        { t: '[+] The source is unexpected; the CDN and DNS beside it are ruled out.', c: 'ok' },
      ], fb: {
        means: 'The source is absent from the reviewed known-good peer list, while the CDN and DNS are on it.',
        changes: 'You can now call it unexpected, not merely unfamiliar — and rule the benign peers out.',
        next: 'You have enough to decide — file your orientation report.',
      } } },

    { key: 'report', cmd: 'submit orientation report', unlock: 3, icon: '📨', name: 'File orientation report', hint: 'submit orientation report' },

    { key: 'block',    cmd: 'block source',     unlock: 5, icon: '⊘', name: 'Block source',     hint: 'block source' },
    { key: 'isolate',  cmd: 'isolate host',     unlock: 5, icon: '🔌', name: 'Isolate host',     hint: 'isolate host' },
    { key: 'escalate', cmd: 'escalate alert',   unlock: 5, icon: '⏫', name: 'Escalate to tier 2', hint: 'escalate alert' },
  ],
  verb: {
    whois: 'whois', ports: 'ports', compare: 'baseline', submit: 'report',
    block: 'block', isolate: 'isolate', escalate: 'escalate',
  },
  doc: {
    ls:     { purpose: 'Get your bearings — see what telemetry was exported before you dig in.',
              learn: 'Before you can investigate anything, you have to know what is in front of you. `ls` ("list") prints the files in the current folder so you can see the telemetry exported from the flagged host.' },
    cat:    { purpose: 'Read the connection snapshot to see who the host is really talking to.',
              learn: '`cat` reads a file out to the terminal. Point it at the connection snapshot to see every address FIN-3310 is talking to — and which one keeps coming back.' },
    grep:   { purpose: 'Pull one suspect address out of a noisy log to see what it reached for.',
              learn: '`grep` prints only the lines of a file that match a pattern. Point it at the suspect address in the access log to see every port it touched.' },
    whois:  { purpose: 'Find out whether the source is an accountable owner or unknown infrastructure.',
              learn: 'Every legitimate service is registered to an organisation with an abuse contact. `whois` reveals that ownership — or, for an unknown source, the lack of it.' },
    ports:  { purpose: 'Tell blind probing apart from a peer using a service you actually offer.',
              learn: 'A real peer connects to a service you actually run. This compares the ports the source reached against the ports FIN-3310 truly listens on — reaching for doors that do not exist is probing.' },
    baseline:{ purpose: 'Decide whether the source is expected or unexpected.',
              learn: 'A baseline is the reviewed list of addresses a host is supposed to talk to. Comparing against it turns "this looks unfamiliar" into "this is unexpected" — and rules out benign peers like the CDN.' },
    report: { purpose: 'Record your determination and close out the orientation.',
              learn: 'Every investigation ends with a determination. Here you pick the conclusion your evidence best supports — the orientation report is multiple-choice.' },
    block:  { purpose: 'Cut off a confirmed-malicious source. (Locked in orientation.)',
              learn: 'Blocking a source at the firewall stops it from reaching you. It is a real response action you learn to use later — orientation is about investigating and deciding, not acting.' },
    isolate:{ purpose: 'Quarantine a compromised host from the network. (Locked in orientation.)',
              learn: 'Isolating a host pulls it off the network so a threat cannot spread. It is a later-stage response action — not needed for an orientation.' },
    escalate:{ purpose: 'Hand a confirmed incident to a senior analyst. (Locked in orientation.)',
              learn: 'Escalation routes a confirmed incident to tier-2 responders. You will practise it in a real assignment — for now, just reach the right determination.' },
  },
  hintFlow: {
    stage1: [
      { type: 'ran', key: 'ls', hint: 'ls' },
      { type: 'read', file: 'network_snapshot.txt', hint: 'cat' },
      { hint: 'grep' },
    ],
    stage2: { group: 'recon', need: 2, toolsHint: 'observe', pinHint: 'pinObs' },
    stage3: { hint: 'analyze' },
    stage4: { group: 'soc', need: 3, toolsHint: 'analyze', pinHint: 'pinFindings' },
    stage5: { required: [], actHint: 'analyze', reportHint: 'reportHint' },
  },
  hints: {
    ls: { id: 'ls', tiers: [
      'Every investigation starts with orientation — get your bearings before you touch anything. You are looking at telemetry exported from the flagged workstation.',
      'A triage folder holds files, and you cannot reason about what you cannot see. Your first job is to find out which files are here.',
      'In Linux, one short two-letter command lists the files in the current folder.',
      'Type `ls` and press Enter to list the files.',
    ] },
    cat: { id: 'cat', tiers: [
      'A good analyst reads the raw evidence first-hand. One file is the live connection snapshot — that is where odd traffic shows itself.',
      'You cannot tell who the host is really talking to without seeing every address it has open. Read the snapshot and look for one that repeats.',
      "Use the command that prints a file's contents to the screen, followed by the snapshot file's name.",
      'Type `cat network_snapshot.txt` to read the connection snapshot.',
    ] },
    grep: { id: 'grep', tiers: [
      'You have a suspect address now. A log can bury a pattern in noise, but the ports an address touched cannot lie — that is what to look at next.',
      'Separate the suspect from the noise: pull every line about that one address out of the access log so you can see what it reached for.',
      'There is a Linux tool that prints only the lines of a file matching a pattern. Use it on the access log with the suspect address.',
      'Type `grep 192.0.2.55 access.log` to surface its activity.',
    ] },
    observe: { id: 'observe', tiers: [
      'You have read the evidence — now make it count. Findings only become a case once they are written down.',
      'Two things stood out: one address keeps coming back, and it touched several ports. Commit both.',
      'Indicators are appearing on the EVIDENCE board to the right — pin the ones you observed.',
      'Type `pin all` to pin every indicator you have surfaced.',
    ] },
    pinObs: { id: 'pinObs', tiers: [
      'Investigating surfaces evidence, but an analyst builds a case from committed indicators, not loose observations.',
      'Pin what you observed so it is on the record before you dig deeper.',
      'Pin both indicators on the evidence board — click a card, or use the pin command.',
      'Type `pin all` to pin every indicator you have surfaced.',
    ] },
    analyze: { id: 'analyze', tiers: [
      'Your job now shifts from observing to confirming. Prove three things about that outside address.',
      'Establish who owns the source, which ports it reached versus what the host runs, and whether it is even an approved peer.',
      'The ANALYST TOOLS group just unlocked — work through them one at a time, then file your orientation report.',
      'Type `whois 192.0.2.55`, then `ports 192.0.2.55` and `compare baseline`; finally `submit orientation report`.',
    ] },
    pinFindings: { id: 'pinFindings', tiers: [
      'Record the confirmations you just uncovered so your determination is backed by evidence.',
      'Pin the findings from your analyst tools on the evidence board.',
      'Pin your findings, then file the orientation report.',
      'Type `pin all`, then `submit orientation report`.',
    ] },
    reportHint: { id: 'reportHint', tiers: [
      'You have investigated who the source is, what it touched, and whether it is expected. Time to decide.',
      'File your orientation report and pick the determination your evidence supports.',
      'Submit the orientation report to finish.',
      'Type `submit orientation report`.',
    ] },
  },
  contain: {},
  containRequired: [],
  reveal: {
    campaign: [
      { t: '' },
      { t: '── PICTURE FORMING ───────────────────────────────', c: 'head' },
      { t: 'You committed your observations. The analyst tools are unlocking — the', c: 'dim' },
      { t: 'network map above will sharpen as you confirm the source. Run `whois`,', c: 'dim' },
      { t: '`ports`, then `compare baseline`, and file your orientation report when ready.', c: 'dim' },
    ],
    containment: [],
  },
  reportDone: [{ t: '[+] Escalation decision recorded. Nice work — that is the core loop of SOC triage: investigate, correlate, then decide.', c: 'ok' }],
  report: {
    head: 'ANALYST ESCALATION DECISION',
    question: 'You have investigated and correlated the evidence. As the analyst on shift, what should happen next with the traffic to FIN-3310?',
    instruction: 'Pick the action your evidence best supports:',
    requireRan: ['whois', 'ports', 'baseline'],
    requireMsg: 'Decide this last. First run your analyst tools — `whois 192.0.2.55`, `ports 192.0.2.55`, and `compare baseline` — so your decision is backed by evidence.',
    choices: [
      { text: 'Escalate it as suspicious reconnaissance — an unknown, unregistered source hit multiple unrelated ports and is not on the known-good baseline.',
        correct: true,
        feedback: '[+] Exactly. Unknown source + multiple unrelated ports + off-baseline = a pattern worth escalating. Escalate and monitor — that is the right analyst call.' },
      { text: 'Close it as normal CDN traffic — nothing unusual here.',
        feedback: 'Re-check your baseline comparison: the repeated source 192.0.2.55 is NOT the CDN, and it is absent from the known-good list.' },
      { text: 'Ignore it — no malware was found on the workstation.',
        feedback: 'Reconnaissance comes before malware. The probing pattern is exactly what you escalate so it is caught early — you do not wait for damage.' },
      { text: 'Block all external traffic to the network immediately.',
        feedback: 'That is an over-reaction. Blocking everything breaks real users and destroys evidence. A single suspicious source is escalated and monitored, not met by shutting down the whole network.' },
    ],
  },
  consequence: [
    { t: '' },
    { t: 'RESPONSE / CONSEQUENCE — what your escalation set in motion', c: 'head' },
    { t: '[+] CyberCorp SOC queue updated — the case is now with a senior analyst.', c: 'ok' },
    { t: '[+] FIN-3310 flagged for monitoring.', c: 'ok' },
    { t: '[+] 192.0.2.55 added to the source watchlist.', c: 'ok' },
    { t: '    No production systems were blocked — escalating and monitoring keeps users working while the case is reviewed.', c: 'dim' },
    { t: 'Early analysts escalate and watch — they do not block everything on sight.', c: 'dim' },
  ],
  scorecard: {
    title: 'Orientation 2 complete — you ran the loop yourself',
    subLead: 'Second case, same instinct: you read a connection snapshot, identified an unknown source, confirmed it with your analyst tools, and made the escalation call.',
    evHead: 'What you confirmed',
    learned: [
      'The triage loop is the same on every case — only the addresses and ports change.',
      'One outside address reaching many unrelated doors (here 22/445/3389/1433) is the shape of probing.',
      '<code>whois</code> and a <em>baseline</em> turn "unfamiliar" into "unexpected"; a benign CDN is ruled out the same way.',
      'You are ready for your first real assignment — investigate first, then decide.',
    ],
  },
  learning: {
    enabled: true,
    terms: ['whois', 'baseline', 'port-scan', 'reconnaissance', 'threat-intel'],
    debrief: {
      whatHappened: 'In this second orientation you reviewed network traffic to workstation FIN-3310 and found one unknown outside address (192.0.2.55) contacting it repeatedly across several unrelated ports.',
      howItWorked: 'A single external source reached ssh, smb, rdp and mssql — services that would not all belong to one legitimate peer — and it was not on the workstation\u2019s known-good baseline. That combination is what makes traffic suspicious.',
      keyEvidence: [
        { label: 'One unknown source, repeated contact', why: 'a legitimate peer usually uses one service; repetition from an unknown address stands out.' },
        { label: 'Multiple unrelated ports touched', why: 'reaching many different services at once looks like probing, not normal use.' },
        { label: 'Not on the known-good baseline', why: 'the baseline is what lets you call a source unexpected rather than just unfamiliar.' },
      ],
      containment: 'In a real incident you would escalate this to a senior analyst and consider blocking the source — those response actions come later in your training. Orientation is about investigating and deciding.',
      whatNotDone: 'You did NOT block all traffic or pull the workstation offline. With a pattern this early, an analyst escalates and monitors first — over-blocking breaks real users and destroys the evidence you would need. Proportionate response is part of the job.',
      concepts: ['whois', 'baseline', 'port-scan', 'reconnaissance'],
      takeaway: 'Suspicious traffic has a pattern: an unknown source, multiple unrelated ports, and a mismatch with the known-good baseline. Spotting that pattern is the core instinct of network triage.',
    },
  },
};
